/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AiActionProposalDtoExpectedRowVersion } from './aiActionProposalDtoExpectedRowVersion';
import type { AiActionProposalDtoEffectiveDateUtc } from './aiActionProposalDtoEffectiveDateUtc';
import type { AiActionProposalDtoConfirmedAtUtc } from './aiActionProposalDtoConfirmedAtUtc';
import type { AiActionProposalDtoCompletedAtUtc } from './aiActionProposalDtoCompletedAtUtc';
import type { AiActionProposalDtoErrorMessage } from './aiActionProposalDtoErrorMessage';

export interface AiActionProposalDto {
  id: string;
  conversationId: string;
  actionCode: string;
  targetEntityType: string;
  targetEntityId: string;
  status: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: AiActionProposalDtoExpectedRowVersion;
  effectiveDateUtc: AiActionProposalDtoEffectiveDateUtc;
  beforeSnapshotJson: string;
  afterSnapshotJson: string;
  impactSummaryJson: string;
  requiredPermission: string;
  proposalHash: string;
  createdAtUtc: string;
  expiresAtUtc: string;
  confirmedAtUtc: AiActionProposalDtoConfirmedAtUtc;
  completedAtUtc: AiActionProposalDtoCompletedAtUtc;
  errorMessage: AiActionProposalDtoErrorMessage;
}
