/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface AiActionDefinition {
  actionCode: string;
  description: string;
  targetModule: string;
  requiredPermission: string;
  inputSchemaJson: string;
  sensitivity: string;
  requiresConfirmation?: boolean;
  effectiveDatePolicy?: string;
  concurrencyPolicy?: string;
  idempotencyPolicy?: string;
}
