/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AiSourceCategory } from './aiSourceCategory';
import type { AiMessageResponseDtoTokensUsed } from './aiMessageResponseDtoTokensUsed';
import type { SourceReferenceDto } from './sourceReferenceDto';
import type { ToolExecutionDto } from './toolExecutionDto';

export interface AiMessageResponseDto {
  messageId: string;
  senderRole: string;
  content: string;
  sourceCategory: AiSourceCategory;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  tokensUsed: AiMessageResponseDtoTokensUsed;
  createdAtUtc: string;
  sources: SourceReferenceDto[];
  toolExecutions: ToolExecutionDto[];
}
