/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AiProposalExecutionResponseDtoErrorMessage } from './aiProposalExecutionResponseDtoErrorMessage';
import type { AiProposalExecutionResponseDtoNewRowVersion } from './aiProposalExecutionResponseDtoNewRowVersion';

export interface AiProposalExecutionResponseDto {
  proposalId: string;
  actionCode: string;
  status: string;
  success: boolean;
  resultPayloadJson: string;
  errorMessage: AiProposalExecutionResponseDtoErrorMessage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  newRowVersion: AiProposalExecutionResponseDtoNewRowVersion;
  executedAtUtc: string;
}
