/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AiToolDefinitionInputSchemaJson } from './aiToolDefinitionInputSchemaJson';
import type { AiToolDefinitionOutputSchemaJson } from './aiToolDefinitionOutputSchemaJson';
import type { AiToolDefinitionTimeoutSeconds } from './aiToolDefinitionTimeoutSeconds';
import type { AiToolDefinitionMaxResultSizeChars } from './aiToolDefinitionMaxResultSizeChars';

export interface AiToolDefinition {
  toolCode: string;
  descriptionEn: string;
  descriptionAr: string;
  requiredPermission: string;
  dataClassification?: string;
  inputSchemaJson?: AiToolDefinitionInputSchemaJson;
  outputSchemaJson?: AiToolDefinitionOutputSchemaJson;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  timeoutSeconds?: AiToolDefinitionTimeoutSeconds;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  maxResultSizeChars?: AiToolDefinitionMaxResultSizeChars;
  isReadOnly?: boolean;
}
