/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApplicationStageHistoryFromStageId } from './applicationStageHistoryFromStageId';
import type { ApplicationStageHistoryReason } from './applicationStageHistoryReason';
import type { ApplicationStageHistoryIdempotencyKey } from './applicationStageHistoryIdempotencyKey';

export interface ApplicationStageHistory {
  id: string;
  applicationId: string;
  fromStageId: ApplicationStageHistoryFromStageId;
  toStageId: string;
  changedByUserId: string;
  changedAtUtc: string;
  reason: ApplicationStageHistoryReason;
  idempotencyKey: ApplicationStageHistoryIdempotencyKey;
}
