/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { LegalEntityId } from './legalEntityId';
import type { ApplicationStatus } from './applicationStatus';
import type { ApplicationSource } from './applicationSource';
import type { ApplicationDisposedAtUtc } from './applicationDisposedAtUtc';
import type { ApplicationDispositionReason } from './applicationDispositionReason';
import type { ApplicationDispositionNote } from './applicationDispositionNote';
import type { ApplicationHiredPersonId } from './applicationHiredPersonId';
import type { ApplicationHiredEmploymentId } from './applicationHiredEmploymentId';
import type { ApplicationHiredAtUtc } from './applicationHiredAtUtc';
import type { ApplicationRowVersion } from './applicationRowVersion';
import type { ApplicationStageHistoryProperty } from './applicationStageHistoryProperty';

export interface Application {
  id: string;
  tenantId: TenantId;
  legalEntityId: LegalEntityId;
  requisitionId: string;
  candidateId: string;
  pipelineVersionId: string;
  currentStageId?: string;
  status?: ApplicationStatus;
  source?: ApplicationSource;
  appliedAtUtc?: string;
  disposedAtUtc?: ApplicationDisposedAtUtc;
  dispositionReason?: ApplicationDispositionReason;
  dispositionNote?: ApplicationDispositionNote;
  hiredPersonId?: ApplicationHiredPersonId;
  hiredEmploymentId?: ApplicationHiredEmploymentId;
  hiredAtUtc?: ApplicationHiredAtUtc;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: ApplicationRowVersion;
  stageHistory?: ApplicationStageHistoryProperty;
}
