/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApplicationStatus } from './applicationStatus';
import type { ApplicationSummaryDtoRowVersion } from './applicationSummaryDtoRowVersion';

export interface ApplicationSummaryDto {
  id: string;
  candidateId: string;
  candidateNameEn: string;
  candidateNameAr: string;
  email: string;
  phoneNumber: string;
  currentStageId: string;
  status: ApplicationStatus;
  appliedAtUtc: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: ApplicationSummaryDtoRowVersion;
}
