/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Application } from './application';
import type { Candidate } from './candidate';
import type { JobRequisition } from './jobRequisition';
import type { ApplicationStageHistory } from './applicationStageHistory';

export interface ApplicationDetailDto {
  application: Application;
  candidate: Candidate;
  requisition: JobRequisition;
  stageHistory: ApplicationStageHistory[];
}
