/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApprovalDecisionHistoryDtoStepOrder } from './approvalDecisionHistoryDtoStepOrder';
import type { ApprovalDecisionHistoryDtoReason } from './approvalDecisionHistoryDtoReason';

export interface ApprovalDecisionHistoryDto {
  id: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  stepOrder: ApprovalDecisionHistoryDtoStepOrder;
  actorUserId: string;
  action: string;
  reason: ApprovalDecisionHistoryDtoReason;
  timestampUtc: string;
}
