/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApprovalInboxItemDtoCurrentStepOrder } from './approvalInboxItemDtoCurrentStepOrder';
import type { ApprovalInboxItemDtoTotalSteps } from './approvalInboxItemDtoTotalSteps';
import type { ApprovalInboxItemDtoRowVersion } from './approvalInboxItemDtoRowVersion';

export interface ApprovalInboxItemDto {
  id: string;
  tenantId: string;
  legalEntityId: string;
  sourceModule: string;
  sourceEntityId: string;
  workflowType: string;
  title: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  currentStepOrder: ApprovalInboxItemDtoCurrentStepOrder;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalSteps: ApprovalInboxItemDtoTotalSteps;
  status: string;
  requesterUserId: string;
  requesterEmploymentId: string;
  createdAt: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: ApprovalInboxItemDtoRowVersion;
}
