/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApprovalRequestDetailDtoCurrentStepOrder } from './approvalRequestDetailDtoCurrentStepOrder';
import type { ApprovalRequestDetailDtoTotalSteps } from './approvalRequestDetailDtoTotalSteps';
import type { ApprovalRequestDetailDtoPayloadSnapshotJson } from './approvalRequestDetailDtoPayloadSnapshotJson';
import type { ApprovalStepDto } from './approvalStepDto';
import type { ApprovalDecisionHistoryDto } from './approvalDecisionHistoryDto';
import type { ApprovalRequestDetailDtoRowVersion } from './approvalRequestDetailDtoRowVersion';

export interface ApprovalRequestDetailDto {
  id: string;
  tenantId: string;
  legalEntityId: string;
  sourceModule: string;
  sourceEntityId: string;
  workflowType: string;
  title: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  currentStepOrder: ApprovalRequestDetailDtoCurrentStepOrder;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalSteps: ApprovalRequestDetailDtoTotalSteps;
  status: string;
  requesterUserId: string;
  requesterEmploymentId: string;
  payloadSnapshotJson: ApprovalRequestDetailDtoPayloadSnapshotJson;
  steps: ApprovalStepDto[];
  history: ApprovalDecisionHistoryDto[];
  createdAt: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: ApprovalRequestDetailDtoRowVersion;
}
