/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApprovalStepDtoStepOrder } from './approvalStepDtoStepOrder';
import type { ApprovalStepDtoAssignedApproverUserId } from './approvalStepDtoAssignedApproverUserId';
import type { ApprovalStepDtoAssignedRole } from './approvalStepDtoAssignedRole';
import type { ApprovalStepDtoDecidedAtUtc } from './approvalStepDtoDecidedAtUtc';
import type { ApprovalStepDtoDecidedByUserId } from './approvalStepDtoDecidedByUserId';
import type { ApprovalStepDtoDecisionReason } from './approvalStepDtoDecisionReason';
import type { ApprovalStepDtoRowVersion } from './approvalStepDtoRowVersion';

export interface ApprovalStepDto {
  id: string;
  approvalRequestId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  stepOrder: ApprovalStepDtoStepOrder;
  assignedApproverUserId: ApprovalStepDtoAssignedApproverUserId;
  assignedRole: ApprovalStepDtoAssignedRole;
  status: string;
  decidedAtUtc: ApprovalStepDtoDecidedAtUtc;
  decidedByUserId: ApprovalStepDtoDecidedByUserId;
  decisionReason: ApprovalStepDtoDecisionReason;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: ApprovalStepDtoRowVersion;
}
