/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApprovalDelegationDtoExpiresAtUtc } from './approvalDelegationDtoExpiresAtUtc';
import type { ApprovalDelegationDtoRevokedAtUtc } from './approvalDelegationDtoRevokedAtUtc';

export interface ApprovalDelegationDto {
  id: string;
  approvalRequestId: string;
  stepOrder: number;
  delegatedFromUserId: string;
  delegatedToUserId: string;
  reason: string;
  createdAtUtc: string;
  expiresAtUtc: ApprovalDelegationDtoExpiresAtUtc;
  revokedAtUtc: ApprovalDelegationDtoRevokedAtUtc;
}
