/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AssignRoleRequestLegalEntityScopeId } from './assignRoleRequestLegalEntityScopeId';
import type { AssignRoleRequestOrganizationUnitScopeId } from './assignRoleRequestOrganizationUnitScopeId';

export interface AssignRoleRequest {
  userId: string;
  roleId: string;
  legalEntityScopeId: AssignRoleRequestLegalEntityScopeId;
  organizationUnitScopeId: AssignRoleRequestOrganizationUnitScopeId;
}
