/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceDayDtoFirstClockInUtc } from './attendanceDayDtoFirstClockInUtc';
import type { AttendanceDayDtoLastClockOutUtc } from './attendanceDayDtoLastClockOutUtc';
import type { AttendanceDayDtoScheduledMinutes } from './attendanceDayDtoScheduledMinutes';
import type { AttendanceDayDtoTotalWorkedMinutes } from './attendanceDayDtoTotalWorkedMinutes';
import type { AttendanceDayDtoLateMinutes } from './attendanceDayDtoLateMinutes';
import type { AttendanceDayDtoEarlyDepartureMinutes } from './attendanceDayDtoEarlyDepartureMinutes';
import type { AttendanceDayDtoRowVersion } from './attendanceDayDtoRowVersion';

export interface AttendanceDayDto {
  id: string;
  tenantId: string;
  legalEntityId: string;
  employmentId: string;
  businessDate: string;
  timeZoneId: string;
  status: string;
  firstClockInUtc: AttendanceDayDtoFirstClockInUtc;
  lastClockOutUtc: AttendanceDayDtoLastClockOutUtc;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  scheduledMinutes: AttendanceDayDtoScheduledMinutes;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalWorkedMinutes: AttendanceDayDtoTotalWorkedMinutes;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  lateMinutes: AttendanceDayDtoLateMinutes;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  earlyDepartureMinutes: AttendanceDayDtoEarlyDepartureMinutes;
  isAbsent: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: AttendanceDayDtoRowVersion;
}
