/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceExceptionDtoResolutionNotes } from './attendanceExceptionDtoResolutionNotes';
import type { AttendanceExceptionDtoResolvedByUserId } from './attendanceExceptionDtoResolvedByUserId';
import type { AttendanceExceptionDtoResolvedAtUtc } from './attendanceExceptionDtoResolvedAtUtc';

export interface AttendanceExceptionDto {
  id: string;
  attendanceDayId: string;
  tenantId: string;
  employmentId: string;
  type: string;
  status: string;
  details: string;
  resolutionNotes: AttendanceExceptionDtoResolutionNotes;
  resolvedByUserId: AttendanceExceptionDtoResolvedByUserId;
  resolvedAtUtc: AttendanceExceptionDtoResolvedAtUtc;
  createdAtUtc: string;
}
