/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { AuditRecordLegalEntityId } from './auditRecordLegalEntityId';
import type { AuditRecordCorrelationId } from './auditRecordCorrelationId';
import type { AuditRecordIpAddress } from './auditRecordIpAddress';
import type { AuditRecordUserAgent } from './auditRecordUserAgent';
import type { AuditRecordReasonCode } from './auditRecordReasonCode';
import type { AuditRecordChangesBeforeJson } from './auditRecordChangesBeforeJson';
import type { AuditRecordChangesAfterJson } from './auditRecordChangesAfterJson';
import type { AuditRecordSafeMetadataJson } from './auditRecordSafeMetadataJson';

export interface AuditRecord {
  id: string;
  tenantId: TenantId;
  legalEntityId: AuditRecordLegalEntityId;
  actorUserId: string;
  actorType: string;
  actionCode: string;
  entityType: string;
  entityId: string;
  occurredAtUtc: string;
  correlationId?: AuditRecordCorrelationId;
  ipAddress?: AuditRecordIpAddress;
  userAgent?: AuditRecordUserAgent;
  reasonCode?: AuditRecordReasonCode;
  changesBeforeJson?: AuditRecordChangesBeforeJson;
  changesAfterJson?: AuditRecordChangesAfterJson;
  safeMetadataJson?: AuditRecordSafeMetadataJson;
  dataClassification?: string;
}
