/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { BackgroundJobDtoCompletedAtUtc } from './backgroundJobDtoCompletedAtUtc';
import type { BackgroundJobDtoError } from './backgroundJobDtoError';

export interface BackgroundJobDto {
  jobId: string;
  operation: string;
  status: string;
  startedAtUtc: string;
  completedAtUtc: BackgroundJobDtoCompletedAtUtc;
  error: BackgroundJobDtoError;
}
