/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CalculationTraceDtoStepOrder } from './calculationTraceDtoStepOrder';
import type { CalculationTraceDtoIntermediateAmount } from './calculationTraceDtoIntermediateAmount';
import type { CalculationTraceDtoRoundingDelta } from './calculationTraceDtoRoundingDelta';
import type { CalculationTraceDtoFinalAmount } from './calculationTraceDtoFinalAmount';

export interface CalculationTraceDto {
  id: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  stepOrder: CalculationTraceDtoStepOrder;
  ruleReference: string;
  description: string;
  formulaApplied: string;
  inputValuesJson: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  intermediateAmount: CalculationTraceDtoIntermediateAmount;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  roundingDelta: CalculationTraceDtoRoundingDelta;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  finalAmount: CalculationTraceDtoFinalAmount;
}
