/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CalculateRunRequestExpectedRowVersion } from './calculateRunRequestExpectedRowVersion';
import type { CalculateRunRequestIdempotencyKey } from './calculateRunRequestIdempotencyKey';

export interface CalculateRunRequest {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: CalculateRunRequestExpectedRowVersion;
  idempotencyKey?: CalculateRunRequestIdempotencyKey;
}
