/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { CandidateLocation } from './candidateLocation';
import type { CandidateHeadline } from './candidateHeadline';
import type { CandidateSource } from './candidateSource';
import type { CandidateResumeDocumentId } from './candidateResumeDocumentId';
import type { CandidateSkillsJson } from './candidateSkillsJson';
import type { CandidateRowVersion } from './candidateRowVersion';

export interface Candidate {
  id: string;
  tenantId: TenantId;
  firstNameEn: string;
  lastNameEn: string;
  firstNameAr: string;
  lastNameAr: string;
  email: string;
  phoneNumber: string;
  location?: CandidateLocation;
  headline?: CandidateHeadline;
  source?: CandidateSource;
  resumeDocumentId?: CandidateResumeDocumentId;
  skillsJson?: CandidateSkillsJson;
  normalizedEmailHash?: string;
  normalizedPhoneHash?: string;
  createdAtUtc?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: CandidateRowVersion;
}
