/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ChangeAssignmentRequestPositionId } from './changeAssignmentRequestPositionId';
import type { ChangeAssignmentRequestLocationId } from './changeAssignmentRequestLocationId';
import type { ChangeAssignmentRequestManagerEmploymentId } from './changeAssignmentRequestManagerEmploymentId';
import type { ChangeAssignmentRequestRowVersion } from './changeAssignmentRequestRowVersion';

export interface ChangeAssignmentRequest {
  organizationUnitId?: string;
  positionId?: ChangeAssignmentRequestPositionId;
  locationId?: ChangeAssignmentRequestLocationId;
  managerEmploymentId?: ChangeAssignmentRequestManagerEmploymentId;
  jobTitleEn?: string;
  jobTitleAr?: string;
  effectiveFrom?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: ChangeAssignmentRequestRowVersion;
}
