/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { CompanyPolicyVersion } from './companyPolicyVersion';
import type { CompanyPolicyEffectiveToUtc } from './companyPolicyEffectiveToUtc';

export interface CompanyPolicy {
  id: string;
  tenantId: TenantId;
  policyCode: string;
  titleEn: string;
  titleAr: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  version: CompanyPolicyVersion;
  effectiveFromUtc: string;
  effectiveToUtc: CompanyPolicyEffectiveToUtc;
  contentEn: string;
  contentAr: string;
  classification?: string;
  isActive?: boolean;
}
