/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationSummaryDtoContextEntityType } from './conversationSummaryDtoContextEntityType';
import type { ConversationSummaryDtoContextEntityId } from './conversationSummaryDtoContextEntityId';
import type { ConversationSummaryDtoMessageCount } from './conversationSummaryDtoMessageCount';

export interface ConversationSummaryDto {
  id: string;
  title: string;
  contextEntityType: ConversationSummaryDtoContextEntityType;
  contextEntityId: ConversationSummaryDtoContextEntityId;
  createdAtUtc: string;
  updatedAtUtc: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  messageCount: ConversationSummaryDtoMessageCount;
}
