/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationDetailDtoContextEntityType } from './conversationDetailDtoContextEntityType';
import type { ConversationDetailDtoContextEntityId } from './conversationDetailDtoContextEntityId';
import type { AiMessageResponseDto } from './aiMessageResponseDto';

export interface ConversationDetailDto {
  id: string;
  title: string;
  contextEntityType: ConversationDetailDtoContextEntityType;
  contextEntityId: ConversationDetailDtoContextEntityId;
  createdAtUtc: string;
  updatedAtUtc: string;
  messages: AiMessageResponseDto[];
}
