/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ConnectorType } from './connectorType';
import type { IntegrationDirection } from './integrationDirection';
import type { IntegrationAuthType } from './integrationAuthType';
import type { CreateConnectorRequestSecretCredential } from './createConnectorRequestSecretCredential';

export interface CreateConnectorRequest {
  code: string;
  nameEn: string;
  nameAr: string;
  connectorType: ConnectorType;
  direction: IntegrationDirection;
  endpointUrl: string;
  authType: IntegrationAuthType;
  secretCredential: CreateConnectorRequestSecretCredential;
  isActive: boolean;
  eventSubscriptionsJson: string;
  configJson: string;
}
