/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateLocationRequestCountry } from './createLocationRequestCountry';
import type { CreateLocationRequestCity } from './createLocationRequestCity';
import type { CreateLocationRequestAddress } from './createLocationRequestAddress';

export interface CreateLocationRequest {
  code?: string;
  nameEn?: string;
  nameAr?: string;
  country?: CreateLocationRequestCountry;
  city?: CreateLocationRequestCity;
  address?: CreateLocationRequestAddress;
}
