/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrganizationUnitRequestLegalEntityId } from './createOrganizationUnitRequestLegalEntityId';
import type { CreateOrganizationUnitRequestParentUnitId } from './createOrganizationUnitRequestParentUnitId';
import type { CreateOrganizationUnitRequestManagerPositionId } from './createOrganizationUnitRequestManagerPositionId';
import type { CreateOrganizationUnitRequestEffectiveTo } from './createOrganizationUnitRequestEffectiveTo';

export interface CreateOrganizationUnitRequest {
  legalEntityId?: CreateOrganizationUnitRequestLegalEntityId;
  code?: string;
  nameEn?: string;
  nameAr?: string;
  type?: string;
  parentUnitId?: CreateOrganizationUnitRequestParentUnitId;
  managerPositionId?: CreateOrganizationUnitRequestManagerPositionId;
  effectiveFrom?: string;
  effectiveTo?: CreateOrganizationUnitRequestEffectiveTo;
}
