/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateLeaveRequestInputDurationDays } from './createLeaveRequestInputDurationDays';
import type { CreateLeaveRequestInputAttachmentDocumentId } from './createLeaveRequestInputAttachmentDocumentId';

export interface CreateLeaveRequestInput {
  employmentId: string;
  leaveTypeId: string;
  startDate: string;
  endDate: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  durationDays: CreateLeaveRequestInputDurationDays;
  reason: string;
  attachmentDocumentId?: CreateLeaveRequestInputAttachmentDocumentId;
}
