/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCandidateRequestLocation } from './createCandidateRequestLocation';
import type { CreateCandidateRequestHeadline } from './createCandidateRequestHeadline';
import type { CreateCandidateRequestSource } from './createCandidateRequestSource';
import type { CreateCandidateRequestResumeDocumentId } from './createCandidateRequestResumeDocumentId';
import type { CreateCandidateRequestSkillsJson } from './createCandidateRequestSkillsJson';

export interface CreateCandidateRequest {
  firstNameEn: string;
  lastNameEn: string;
  firstNameAr: string;
  lastNameAr: string;
  email: string;
  phoneNumber: string;
  location: CreateCandidateRequestLocation;
  headline: CreateCandidateRequestHeadline;
  source: CreateCandidateRequestSource;
  resumeDocumentId: CreateCandidateRequestResumeDocumentId;
  skillsJson: CreateCandidateRequestSkillsJson;
}
