/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateProposalRequestExpectedRowVersion } from './createProposalRequestExpectedRowVersion';
import type { CreateProposalRequestEffectiveDateUtc } from './createProposalRequestEffectiveDateUtc';
import type { CreateProposalRequestBeforeSnapshotJson } from './createProposalRequestBeforeSnapshotJson';
import type { CreateProposalRequestAfterSnapshotJson } from './createProposalRequestAfterSnapshotJson';
import type { CreateProposalRequestImpactSummaryJson } from './createProposalRequestImpactSummaryJson';
import type { CreateProposalRequestValidityMinutes } from './createProposalRequestValidityMinutes';

export interface CreateProposalRequest {
  conversationId: string;
  actionCode: string;
  targetEntityType: string;
  targetEntityId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: CreateProposalRequestExpectedRowVersion;
  effectiveDateUtc: CreateProposalRequestEffectiveDateUtc;
  beforeSnapshotJson: CreateProposalRequestBeforeSnapshotJson;
  afterSnapshotJson: CreateProposalRequestAfterSnapshotJson;
  impactSummaryJson: CreateProposalRequestImpactSummaryJson;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  validityMinutes?: CreateProposalRequestValidityMinutes;
}
