/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreatePositionRequestLegalEntityId } from './createPositionRequestLegalEntityId';
import type { CreatePositionRequestGrade } from './createPositionRequestGrade';

export interface CreatePositionRequest {
  legalEntityId?: CreatePositionRequestLegalEntityId;
  organizationUnitId: string;
  jobCode: string;
  titleEn: string;
  titleAr: string;
  grade?: CreatePositionRequestGrade;
}
