/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateEmployeeRequestLegalEntityId } from './createEmployeeRequestLegalEntityId';
import type { CreateEmployeeRequestEmployeeNumber } from './createEmployeeRequestEmployeeNumber';
import type { CreateEmployeeRequestGender } from './createEmployeeRequestGender';
import type { CreateEmployeeRequestNationality } from './createEmployeeRequestNationality';
import type { CreateEmployeeRequestPrimaryEmail } from './createEmployeeRequestPrimaryEmail';
import type { CreateEmployeeRequestPhoneNumber } from './createEmployeeRequestPhoneNumber';
import type { CreateEmployeeRequestPositionId } from './createEmployeeRequestPositionId';
import type { CreateEmployeeRequestLocationId } from './createEmployeeRequestLocationId';
import type { CreateEmployeeRequestManagerEmploymentId } from './createEmployeeRequestManagerEmploymentId';

export interface CreateEmployeeRequest {
  legalEntityId?: CreateEmployeeRequestLegalEntityId;
  employeeNumber: CreateEmployeeRequestEmployeeNumber;
  firstNameEn: string;
  lastNameEn: string;
  firstNameAr: string;
  lastNameAr: string;
  dateOfBirth: string;
  gender?: CreateEmployeeRequestGender;
  nationality?: CreateEmployeeRequestNationality;
  nationalIdentifier: string;
  primaryEmail?: CreateEmployeeRequestPrimaryEmail;
  phoneNumber?: CreateEmployeeRequestPhoneNumber;
  hireDate: string;
  organizationUnitId: string;
  positionId?: CreateEmployeeRequestPositionId;
  locationId?: CreateEmployeeRequestLocationId;
  managerEmploymentId?: CreateEmployeeRequestManagerEmploymentId;
  jobTitleEn: string;
  jobTitleAr: string;
}
