/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateConversationRequestTitle } from './createConversationRequestTitle';
import type { CreateConversationRequestContextEntityType } from './createConversationRequestContextEntityType';
import type { CreateConversationRequestContextEntityId } from './createConversationRequestContextEntityId';

export interface CreateConversationRequest {
  title?: CreateConversationRequestTitle;
  contextEntityType?: CreateConversationRequestContextEntityType;
  contextEntityId?: CreateConversationRequestContextEntityId;
}
