/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateSavedViewRequest {
  viewName: string;
  isTenantShared: boolean;
  filtersJson: string;
  columnsJson: string;
  sortJson: string;
  groupingJson: string;
}
