/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOfferRequestBaseSalaryMonthly } from './createOfferRequestBaseSalaryMonthly';
import type { CreateOfferRequestAllowancesJson } from './createOfferRequestAllowancesJson';
import type { CreateOfferRequestConditionsNote } from './createOfferRequestConditionsNote';
import type { CreateOfferRequestExpiryDate } from './createOfferRequestExpiryDate';
import type { CreateOfferRequestOfferDocumentId } from './createOfferRequestOfferDocumentId';

export interface CreateOfferRequest {
  applicationId: string;
  candidateId: string;
  titleEn: string;
  titleAr: string;
  proposedStartDate: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  baseSalaryMonthly: CreateOfferRequestBaseSalaryMonthly;
  currency: string;
  allowancesJson: CreateOfferRequestAllowancesJson;
  conditionsNote: CreateOfferRequestConditionsNote;
  expiryDate: CreateOfferRequestExpiryDate;
  offerDocumentId: CreateOfferRequestOfferDocumentId;
}
