/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { CreateRequisitionRequestPositionId } from './createRequisitionRequestPositionId';
import type { CreateRequisitionRequestLocationId } from './createRequisitionRequestLocationId';
import type { CreateRequisitionRequestOpeningsCount } from './createRequisitionRequestOpeningsCount';
import type { CreateRequisitionRequestPipelineId } from './createRequisitionRequestPipelineId';
import type { CreateRequisitionRequestRequisitionReason } from './createRequisitionRequestRequisitionReason';
import type { CreateRequisitionRequestTargetStartDate } from './createRequisitionRequestTargetStartDate';

export interface CreateRequisitionRequest {
  organizationUnitId: string;
  positionId: CreateRequisitionRequestPositionId;
  locationId: CreateRequisitionRequestLocationId;
  hiringManagerId: string;
  recruiterId: string;
  requisitionNumber: string;
  titleEn: string;
  titleAr: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  openingsCount: CreateRequisitionRequestOpeningsCount;
  employmentType: string;
  pipelineId: CreateRequisitionRequestPipelineId;
  requisitionReason: CreateRequisitionRequestRequisitionReason;
  targetStartDate: CreateRequisitionRequestTargetStartDate;
}
