/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentTypeDtoMaxSizeBytes } from './documentTypeDtoMaxSizeBytes';

export interface DocumentTypeDto {
  id?: string;
  code?: string;
  nameEn?: string;
  nameAr?: string;
  isRequired?: boolean;
  requiresExpiryDate?: boolean;
  allowedMimeTypes?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  maxSizeBytes?: DocumentTypeDtoMaxSizeBytes;
}
