/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentVersionDtoVersionNumber } from './documentVersionDtoVersionNumber';
import type { DocumentVersionDtoFileSize } from './documentVersionDtoFileSize';

export interface DocumentVersionDto {
  id?: string;
  documentId?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  versionNumber?: DocumentVersionDtoVersionNumber;
  fileName?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  fileSize?: DocumentVersionDtoFileSize;
  contentType?: string;
  sha256Checksum?: string;
  uploadedAt?: string;
  uploadedBy?: string;
}
