/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentVersionDto } from './documentVersionDto';
import type { DocumentDetailDtoExpiryDate } from './documentDetailDtoExpiryDate';
import type { DocumentDetailDtoLatestVersionNumber } from './documentDetailDtoLatestVersionNumber';
import type { DocumentDetailDtoLatestFileSize } from './documentDetailDtoLatestFileSize';

export interface DocumentDetailDto {
  versions?: DocumentVersionDto[];
  id?: string;
  tenantId?: string;
  legalEntityId?: string;
  ownerType?: string;
  ownerId?: string;
  documentTypeId?: string;
  documentTypeCode?: string;
  documentTypeNameEn?: string;
  documentTypeNameAr?: string;
  title?: string;
  status?: string;
  expiryDate?: DocumentDetailDtoExpiryDate;
  createdAt?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  latestVersionNumber?: DocumentDetailDtoLatestVersionNumber;
  latestFileName?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  latestFileSize?: DocumentDetailDtoLatestFileSize;
  latestContentType?: string;
}
