/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DocumentSummaryDtoExpiryDate } from './documentSummaryDtoExpiryDate';
import type { DocumentSummaryDtoLatestVersionNumber } from './documentSummaryDtoLatestVersionNumber';
import type { DocumentSummaryDtoLatestFileSize } from './documentSummaryDtoLatestFileSize';

export interface DocumentSummaryDto {
  id?: string;
  tenantId?: string;
  legalEntityId?: string;
  ownerType?: string;
  ownerId?: string;
  documentTypeId?: string;
  documentTypeCode?: string;
  documentTypeNameEn?: string;
  documentTypeNameAr?: string;
  title?: string;
  status?: string;
  expiryDate?: DocumentSummaryDtoExpiryDate;
  createdAt?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  latestVersionNumber?: DocumentSummaryDtoLatestVersionNumber;
  latestFileName?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  latestFileSize?: DocumentSummaryDtoLatestFileSize;
  latestContentType?: string;
}
