/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EmployeeSummaryDtoRowVersion } from './employeeSummaryDtoRowVersion';

export interface EmployeeSummaryDto {
  id?: string;
  tenantId?: string;
  legalEntityId?: string;
  employeeNumber?: string;
  firstNameEn?: string;
  lastNameEn?: string;
  firstNameAr?: string;
  lastNameAr?: string;
  fullNameEn?: string;
  fullNameAr?: string;
  primaryEmail?: string;
  phoneNumber?: string;
  departmentNameEn?: string;
  departmentNameAr?: string;
  jobTitleEn?: string;
  jobTitleAr?: string;
  locationNameEn?: string;
  status?: string;
  hireDate?: string;
  maskedNationalId?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: EmployeeSummaryDtoRowVersion;
}
