/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EmployeeProfileDtoProbationEndDate } from './employeeProfileDtoProbationEndDate';
import type { EmployeeProfileDtoTerminationDate } from './employeeProfileDtoTerminationDate';
import type { EmployeeProfileDtoTerminationReason } from './employeeProfileDtoTerminationReason';
import type { EmployeeProfileDtoRowVersion } from './employeeProfileDtoRowVersion';
import type { EmployeeProfileDtoCurrentAssignment } from './employeeProfileDtoCurrentAssignment';
import type { EmployeeAssignmentDto } from './employeeAssignmentDto';

export interface EmployeeProfileDto {
  id?: string;
  personId?: string;
  tenantId?: string;
  legalEntityId?: string;
  employeeNumber?: string;
  firstNameEn?: string;
  lastNameEn?: string;
  firstNameAr?: string;
  lastNameAr?: string;
  fullNameEn?: string;
  fullNameAr?: string;
  gender?: string;
  nationality?: string;
  maskedDateOfBirth?: string;
  maskedNationalId?: string;
  primaryEmail?: string;
  phoneNumber?: string;
  status?: string;
  hireDate?: string;
  probationEndDate?: EmployeeProfileDtoProbationEndDate;
  terminationDate?: EmployeeProfileDtoTerminationDate;
  terminationReason?: EmployeeProfileDtoTerminationReason;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: EmployeeProfileDtoRowVersion;
  currentAssignment?: EmployeeProfileDtoCurrentAssignment;
  assignmentHistory?: EmployeeAssignmentDto[];
}
