/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EmployeeAssignmentDtoPositionId } from './employeeAssignmentDtoPositionId';
import type { EmployeeAssignmentDtoLocationId } from './employeeAssignmentDtoLocationId';
import type { EmployeeAssignmentDtoManagerEmploymentId } from './employeeAssignmentDtoManagerEmploymentId';
import type { EmployeeAssignmentDtoManagerNameEn } from './employeeAssignmentDtoManagerNameEn';
import type { EmployeeAssignmentDtoEffectiveTo } from './employeeAssignmentDtoEffectiveTo';

export interface EmployeeAssignmentDto {
  id?: string;
  employmentId?: string;
  organizationUnitId?: string;
  departmentNameEn?: string;
  departmentNameAr?: string;
  positionId?: EmployeeAssignmentDtoPositionId;
  locationId?: EmployeeAssignmentDtoLocationId;
  locationNameEn?: string;
  managerEmploymentId?: EmployeeAssignmentDtoManagerEmploymentId;
  managerNameEn?: EmployeeAssignmentDtoManagerNameEn;
  jobTitleEn?: string;
  jobTitleAr?: string;
  effectiveFrom?: string;
  effectiveTo?: EmployeeAssignmentDtoEffectiveTo;
  isCurrent?: boolean;
}
