/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1AuditParams = {
ActorUserId?: string;
ActionCode?: string;
EntityType?: string;
EntityId?: string;
CorrelationId?: string;
LegalEntityId?: string;
FromUtc?: string;
ToUtc?: string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
Page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
PageSize?: number | string;
};
