/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DeliveryStatus } from './deliveryStatus';

export type GetApiV1IntegrationsDeliveriesParams = {
connectorId?: string;
status?: DeliveryStatus;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
page?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
pageSize?: number | string;
};
