/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { HireCandidateRequestEmployeeNumber } from './hireCandidateRequestEmployeeNumber';
import type { HireCandidateRequestNationalIdentifier } from './hireCandidateRequestNationalIdentifier';
import type { HireCandidateRequestDateOfBirth } from './hireCandidateRequestDateOfBirth';
import type { HireCandidateRequestGender } from './hireCandidateRequestGender';
import type { HireCandidateRequestNationality } from './hireCandidateRequestNationality';
import type { HireCandidateRequestExpectedRowVersion } from './hireCandidateRequestExpectedRowVersion';

export interface HireCandidateRequest {
  hireDate: string;
  employeeNumber: HireCandidateRequestEmployeeNumber;
  nationalIdentifier: HireCandidateRequestNationalIdentifier;
  dateOfBirth: HireCandidateRequestDateOfBirth;
  gender: HireCandidateRequestGender;
  nationality: HireCandidateRequestNationality;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: HireCandidateRequestExpectedRowVersion;
}
