/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { DeliveryStatus } from './deliveryStatus';
import type { IntegrationDeliveryJobAttemptCount } from './integrationDeliveryJobAttemptCount';
import type { IntegrationDeliveryJobMaxAttempts } from './integrationDeliveryJobMaxAttempts';
import type { IntegrationDeliveryJobNextAttemptAtUtc } from './integrationDeliveryJobNextAttemptAtUtc';
import type { IntegrationDeliveryJobLastAttemptAtUtc } from './integrationDeliveryJobLastAttemptAtUtc';
import type { IntegrationDeliveryJobLastHttpStatus } from './integrationDeliveryJobLastHttpStatus';
import type { IntegrationDeliveryJobLastErrorMessage } from './integrationDeliveryJobLastErrorMessage';

export interface IntegrationDeliveryJob {
  id: string;
  tenantId: TenantId;
  connectorId: string;
  eventId: string;
  eventType: string;
  status?: DeliveryStatus;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  attemptCount?: IntegrationDeliveryJobAttemptCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  maxAttempts?: IntegrationDeliveryJobMaxAttempts;
  nextAttemptAtUtc?: IntegrationDeliveryJobNextAttemptAtUtc;
  lastAttemptAtUtc?: IntegrationDeliveryJobLastAttemptAtUtc;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  lastHttpStatus?: IntegrationDeliveryJobLastHttpStatus;
  lastErrorMessage?: IntegrationDeliveryJobLastErrorMessage;
  payloadJson: string;
  idempotencyKey: string;
  createdAtUtc?: string;
}
