/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { InterviewType } from './interviewType';
import type { InterviewLocationOrMeetingUrl } from './interviewLocationOrMeetingUrl';
import type { InterviewStatus } from './interviewStatus';
import type { InterviewInterviewKitJson } from './interviewInterviewKitJson';
import type { InterviewRowVersion } from './interviewRowVersion';
import type { InterviewParticipants } from './interviewParticipants';
import type { InterviewScorecards } from './interviewScorecards';

export interface Interview {
  id: string;
  tenantId: TenantId;
  applicationId: string;
  stageId: string;
  title: string;
  interviewType: InterviewType;
  scheduledStartUtc: string;
  scheduledEndUtc: string;
  timezone: string;
  locationOrMeetingUrl?: InterviewLocationOrMeetingUrl;
  status?: InterviewStatus;
  interviewKitJson?: InterviewInterviewKitJson;
  createdAtUtc?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: InterviewRowVersion;
  participants?: InterviewParticipants;
  scorecards?: InterviewScorecards;
}
