/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { ConnectorType } from './connectorType';
import type { IntegrationDirection } from './integrationDirection';
import type { IntegrationAuthType } from './integrationAuthType';
import type { IntegrationConnectorEncryptedCredentials } from './integrationConnectorEncryptedCredentials';
import type { IntegrationConnectorCredentialsKeyVersion } from './integrationConnectorCredentialsKeyVersion';
import type { IntegrationConnectorRowVersion } from './integrationConnectorRowVersion';

export interface IntegrationConnector {
  id: string;
  tenantId: TenantId;
  code: string;
  nameEn: string;
  nameAr: string;
  connectorType: ConnectorType;
  direction: IntegrationDirection;
  endpointUrl: string;
  authType: IntegrationAuthType;
  encryptedCredentials?: IntegrationConnectorEncryptedCredentials;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  credentialsKeyVersion?: IntegrationConnectorCredentialsKeyVersion;
  isActive?: boolean;
  eventSubscriptionsJson?: string;
  configJson?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: IntegrationConnectorRowVersion;
}
