/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { LegalEntityId } from './legalEntityId';
import type { JobRequisitionPositionId } from './jobRequisitionPositionId';
import type { JobRequisitionLocationId } from './jobRequisitionLocationId';
import type { JobRequisitionOpeningsCount } from './jobRequisitionOpeningsCount';
import type { JobRequisitionPipelineVersion } from './jobRequisitionPipelineVersion';
import type { RequisitionStatus } from './requisitionStatus';
import type { JobRequisitionApprovalRequestId } from './jobRequisitionApprovalRequestId';
import type { JobRequisitionRequisitionReason } from './jobRequisitionRequisitionReason';
import type { JobRequisitionTargetStartDate } from './jobRequisitionTargetStartDate';
import type { JobRequisitionOpenedAtUtc } from './jobRequisitionOpenedAtUtc';
import type { JobRequisitionClosedAtUtc } from './jobRequisitionClosedAtUtc';
import type { JobRequisitionRowVersion } from './jobRequisitionRowVersion';

export interface JobRequisition {
  id: string;
  tenantId: TenantId;
  legalEntityId: LegalEntityId;
  organizationUnitId: string;
  positionId: JobRequisitionPositionId;
  locationId: JobRequisitionLocationId;
  hiringManagerId: string;
  recruiterId: string;
  requisitionNumber: string;
  titleEn: string;
  titleAr: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  openingsCount: JobRequisitionOpeningsCount;
  employmentType: string;
  pipelineId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pipelineVersion: JobRequisitionPipelineVersion;
  status?: RequisitionStatus;
  approvalRequestId?: JobRequisitionApprovalRequestId;
  requisitionReason?: JobRequisitionRequisitionReason;
  targetStartDate?: JobRequisitionTargetStartDate;
  openedAtUtc?: JobRequisitionOpenedAtUtc;
  closedAtUtc?: JobRequisitionClosedAtUtc;
  createdAtUtc?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: JobRequisitionRowVersion;
}
