/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LeaveBalanceDtoYear } from './leaveBalanceDtoYear';
import type { LeaveBalanceDtoEntitledDays } from './leaveBalanceDtoEntitledDays';
import type { LeaveBalanceDtoAccruedDays } from './leaveBalanceDtoAccruedDays';
import type { LeaveBalanceDtoUsedDays } from './leaveBalanceDtoUsedDays';
import type { LeaveBalanceDtoPendingDays } from './leaveBalanceDtoPendingDays';
import type { LeaveBalanceDtoAvailableDays } from './leaveBalanceDtoAvailableDays';
import type { LeaveBalanceDtoRowVersion } from './leaveBalanceDtoRowVersion';

export interface LeaveBalanceDto {
  id: string;
  tenantId: string;
  employmentId: string;
  leaveTypeId: string;
  leaveTypeCode: string;
  leaveTypeNameEn: string;
  leaveTypeNameAr: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  year: LeaveBalanceDtoYear;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  entitledDays: LeaveBalanceDtoEntitledDays;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  accruedDays: LeaveBalanceDtoAccruedDays;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  usedDays: LeaveBalanceDtoUsedDays;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  pendingDays: LeaveBalanceDtoPendingDays;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  availableDays: LeaveBalanceDtoAvailableDays;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: LeaveBalanceDtoRowVersion;
}
