/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LeaveRequestDtoDurationDays } from './leaveRequestDtoDurationDays';
import type { LeaveRequestDtoDurationMinutes } from './leaveRequestDtoDurationMinutes';
import type { LeaveRequestDtoAttachmentDocumentId } from './leaveRequestDtoAttachmentDocumentId';
import type { LeaveRequestDtoApprovalRequestId } from './leaveRequestDtoApprovalRequestId';
import type { LeaveRequestDtoRejectionReason } from './leaveRequestDtoRejectionReason';
import type { LeaveRequestDtoRowVersion } from './leaveRequestDtoRowVersion';

export interface LeaveRequestDto {
  id: string;
  tenantId: string;
  legalEntityId: string;
  employmentId: string;
  leaveTypeId: string;
  leaveTypeCode: string;
  leaveTypeNameEn: string;
  leaveTypeNameAr: string;
  startDate: string;
  endDate: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  durationDays: LeaveRequestDtoDurationDays;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  durationMinutes: LeaveRequestDtoDurationMinutes;
  status: string;
  reason: string;
  attachmentDocumentId: LeaveRequestDtoAttachmentDocumentId;
  approvalRequestId: LeaveRequestDtoApprovalRequestId;
  rejectionReason: LeaveRequestDtoRejectionReason;
  createdAt: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: LeaveRequestDtoRowVersion;
}
