/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LegalEntityDtoRowVersion } from './legalEntityDtoRowVersion';

export interface LegalEntityDto {
  id: string;
  tenantId: string;
  code: string;
  nameEn: string;
  nameAr: string;
  countryCode: string;
  currencyCode: string;
  timezoneId: string;
  isActive: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: LegalEntityDtoRowVersion;
}
