/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PayrollInputSnapshotDto } from './payrollInputSnapshotDto';
import type { LoadInputsRequestExpectedRowVersion } from './loadInputsRequestExpectedRowVersion';

export interface LoadInputsRequest {
  snapshots: PayrollInputSnapshotDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: LoadInputsRequestExpectedRowVersion;
}
