/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface LocationDto {
  id?: string;
  tenantId?: string;
  legalEntityId?: string;
  code?: string;
  nameEn?: string;
  nameAr?: string;
  country?: string;
  city?: string;
  address?: string;
  isActive?: boolean;
}
