/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MoveApplicationStageRequestReason } from './moveApplicationStageRequestReason';
import type { MoveApplicationStageRequestIdempotencyKey } from './moveApplicationStageRequestIdempotencyKey';
import type { MoveApplicationStageRequestExpectedRowVersion } from './moveApplicationStageRequestExpectedRowVersion';

export interface MoveApplicationStageRequest {
  targetStageId: string;
  reason: MoveApplicationStageRequestReason;
  idempotencyKey: MoveApplicationStageRequestIdempotencyKey;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: MoveApplicationStageRequestExpectedRowVersion;
}
