/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';

export interface NotificationPreference {
  id: string;
  tenantId: TenantId;
  userId: string;
  category: string;
  allowEmail?: boolean;
  allowInApp?: boolean;
  allowPush?: boolean;
}
