/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { DeliveryChannel } from './deliveryChannel';
import type { NotificationTemplateVersion } from './notificationTemplateVersion';

export interface NotificationTemplate {
  id: string;
  tenantId: TenantId;
  templateCode: string;
  locale: string;
  subject: string;
  bodyTemplate: string;
  allowedVariablesJson: string;
  channel: DeliveryChannel;
  isActive?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  version?: NotificationTemplateVersion;
}
