/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { NotificationDeepLinkUrl } from './notificationDeepLinkUrl';
import type { DeliveryChannel } from './deliveryChannel';
import type { TransportStatus } from './transportStatus';
import type { NotificationReadAtUtc } from './notificationReadAtUtc';
import type { NotificationSourceEventId } from './notificationSourceEventId';
import type { NotificationIdempotencyKey } from './notificationIdempotencyKey';

export interface Notification {
  id: string;
  tenantId: TenantId;
  recipientUserId: string;
  category: string;
  titleEn: string;
  titleAr: string;
  bodyEn: string;
  bodyAr: string;
  deepLinkUrl?: NotificationDeepLinkUrl;
  channel?: DeliveryChannel;
  status?: TransportStatus;
  isRead?: boolean;
  readAtUtc?: NotificationReadAtUtc;
  isArchived?: boolean;
  createdAtUtc?: string;
  sourceEventId?: NotificationSourceEventId;
  idempotencyKey?: NotificationIdempotencyKey;
}
