/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OfferDetailDtoOfferVersionNumber } from './offerDetailDtoOfferVersionNumber';
import type { OfferDetailDtoBaseSalaryMonthly } from './offerDetailDtoBaseSalaryMonthly';
import type { OfferDetailDtoAllowancesJson } from './offerDetailDtoAllowancesJson';
import type { OfferDetailDtoConditionsNote } from './offerDetailDtoConditionsNote';
import type { OfferStatus } from './offerStatus';
import type { OfferDetailDtoApprovalRequestId } from './offerDetailDtoApprovalRequestId';
import type { OfferDetailDtoIssuedAtUtc } from './offerDetailDtoIssuedAtUtc';
import type { OfferDetailDtoAcceptedAtUtc } from './offerDetailDtoAcceptedAtUtc';
import type { OfferDetailDtoExpiryDate } from './offerDetailDtoExpiryDate';
import type { OfferDetailDtoOfferDocumentId } from './offerDetailDtoOfferDocumentId';
import type { OfferDetailDtoRowVersion } from './offerDetailDtoRowVersion';

export interface OfferDetailDto {
  id: string;
  tenantId: string;
  legalEntityId: string;
  applicationId: string;
  candidateId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  offerVersionNumber: OfferDetailDtoOfferVersionNumber;
  titleEn: string;
  titleAr: string;
  proposedStartDate: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  baseSalaryMonthly: OfferDetailDtoBaseSalaryMonthly;
  currency: string;
  allowancesJson: OfferDetailDtoAllowancesJson;
  conditionsNote: OfferDetailDtoConditionsNote;
  status: OfferStatus;
  approvalRequestId: OfferDetailDtoApprovalRequestId;
  issuedAtUtc: OfferDetailDtoIssuedAtUtc;
  acceptedAtUtc: OfferDetailDtoAcceptedAtUtc;
  expiryDate: OfferDetailDtoExpiryDate;
  offerDocumentId: OfferDetailDtoOfferDocumentId;
  createdAtUtc: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: OfferDetailDtoRowVersion;
}
