/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationUnitDtoParentUnitId } from './organizationUnitDtoParentUnitId';
import type { OrganizationUnitDtoParentNameEn } from './organizationUnitDtoParentNameEn';
import type { OrganizationUnitDtoManagerPositionId } from './organizationUnitDtoManagerPositionId';
import type { OrganizationUnitDtoEffectiveTo } from './organizationUnitDtoEffectiveTo';
import type { OrganizationUnitDtoRowVersion } from './organizationUnitDtoRowVersion';

export interface OrganizationUnitDto {
  id?: string;
  tenantId?: string;
  legalEntityId?: string;
  code?: string;
  nameEn?: string;
  nameAr?: string;
  type?: string;
  parentUnitId?: OrganizationUnitDtoParentUnitId;
  parentNameEn?: OrganizationUnitDtoParentNameEn;
  managerPositionId?: OrganizationUnitDtoManagerPositionId;
  isActive?: boolean;
  effectiveFrom?: string;
  effectiveTo?: OrganizationUnitDtoEffectiveTo;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: OrganizationUnitDtoRowVersion;
}
