/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceExceptionDto } from './attendanceExceptionDto';
import type { PagedExceptionsResponseTotalCount } from './pagedExceptionsResponseTotalCount';
import type { PagedExceptionsResponsePage } from './pagedExceptionsResponsePage';
import type { PagedExceptionsResponsePageSize } from './pagedExceptionsResponsePageSize';

export interface PagedExceptionsResponse {
  items: AttendanceExceptionDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: PagedExceptionsResponseTotalCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: PagedExceptionsResponsePage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: PagedExceptionsResponsePageSize;
}
