/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { JobRequisition } from './jobRequisition';
import type { PagedRecruitmentResultOfJobRequisitionTotalCount } from './pagedRecruitmentResultOfJobRequisitionTotalCount';
import type { PagedRecruitmentResultOfJobRequisitionPage } from './pagedRecruitmentResultOfJobRequisitionPage';
import type { PagedRecruitmentResultOfJobRequisitionPageSize } from './pagedRecruitmentResultOfJobRequisitionPageSize';

export interface PagedRecruitmentResultOfJobRequisition {
  items: JobRequisition[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: PagedRecruitmentResultOfJobRequisitionTotalCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: PagedRecruitmentResultOfJobRequisitionPage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: PagedRecruitmentResultOfJobRequisitionPageSize;
}
