/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ApprovalInboxItemDto } from './approvalInboxItemDto';
import type { PagedApprovalInboxResponseTotalCount } from './pagedApprovalInboxResponseTotalCount';
import type { PagedApprovalInboxResponsePage } from './pagedApprovalInboxResponsePage';
import type { PagedApprovalInboxResponsePageSize } from './pagedApprovalInboxResponsePageSize';

export interface PagedApprovalInboxResponse {
  items: ApprovalInboxItemDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: PagedApprovalInboxResponseTotalCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: PagedApprovalInboxResponsePage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: PagedApprovalInboxResponsePageSize;
}
