/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Application } from './application';
import type { PagedRecruitmentResultOfApplicationTotalCount } from './pagedRecruitmentResultOfApplicationTotalCount';
import type { PagedRecruitmentResultOfApplicationPage } from './pagedRecruitmentResultOfApplicationPage';
import type { PagedRecruitmentResultOfApplicationPageSize } from './pagedRecruitmentResultOfApplicationPageSize';

export interface PagedRecruitmentResultOfApplication {
  items: Application[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: PagedRecruitmentResultOfApplicationTotalCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: PagedRecruitmentResultOfApplicationPage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: PagedRecruitmentResultOfApplicationPageSize;
}
