/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceDayDto } from './attendanceDayDto';
import type { PagedAttendanceDaysResponseTotalCount } from './pagedAttendanceDaysResponseTotalCount';
import type { PagedAttendanceDaysResponsePage } from './pagedAttendanceDaysResponsePage';
import type { PagedAttendanceDaysResponsePageSize } from './pagedAttendanceDaysResponsePageSize';

export interface PagedAttendanceDaysResponse {
  items: AttendanceDayDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: PagedAttendanceDaysResponseTotalCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: PagedAttendanceDaysResponsePage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: PagedAttendanceDaysResponsePageSize;
}
