/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { IntegrationDeliveryJob } from './integrationDeliveryJob';
import type { PagedDeliveriesResultTotalCount } from './pagedDeliveriesResultTotalCount';
import type { PagedDeliveriesResultPage } from './pagedDeliveriesResultPage';
import type { PagedDeliveriesResultPageSize } from './pagedDeliveriesResultPageSize';

export interface PagedDeliveriesResult {
  items: IntegrationDeliveryJob[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: PagedDeliveriesResultTotalCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: PagedDeliveriesResultPage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: PagedDeliveriesResultPageSize;
}
