/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AuditRecord } from './auditRecord';
import type { PagedAuditResultTotalCount } from './pagedAuditResultTotalCount';
import type { PagedAuditResultPage } from './pagedAuditResultPage';
import type { PagedAuditResultPageSize } from './pagedAuditResultPageSize';

export interface PagedAuditResult {
  items: AuditRecord[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: PagedAuditResultTotalCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: PagedAuditResultPage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: PagedAuditResultPageSize;
}
