/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EmployeeSummaryDto } from './employeeSummaryDto';
import type { PagedResultOfEmployeeSummaryDtoTotalCount } from './pagedResultOfEmployeeSummaryDtoTotalCount';
import type { PagedResultOfEmployeeSummaryDtoPageNumber } from './pagedResultOfEmployeeSummaryDtoPageNumber';
import type { PagedResultOfEmployeeSummaryDtoPageSize } from './pagedResultOfEmployeeSummaryDtoPageSize';
import type { PagedResultOfEmployeeSummaryDtoTotalPages } from './pagedResultOfEmployeeSummaryDtoTotalPages';

export interface PagedResultOfEmployeeSummaryDto {
  items?: EmployeeSummaryDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: PagedResultOfEmployeeSummaryDtoTotalCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageNumber?: PagedResultOfEmployeeSummaryDtoPageNumber;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: PagedResultOfEmployeeSummaryDtoPageSize;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalPages?: PagedResultOfEmployeeSummaryDtoTotalPages;
}
