/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Notification } from './notification';
import type { PagedNotificationsResultTotalCount } from './pagedNotificationsResultTotalCount';
import type { PagedNotificationsResultUnreadCount } from './pagedNotificationsResultUnreadCount';
import type { PagedNotificationsResultPage } from './pagedNotificationsResultPage';
import type { PagedNotificationsResultPageSize } from './pagedNotificationsResultPageSize';

export interface PagedNotificationsResult {
  items: Notification[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: PagedNotificationsResultTotalCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  unreadCount: PagedNotificationsResultUnreadCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: PagedNotificationsResultPage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: PagedNotificationsResultPageSize;
}
