/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Candidate } from './candidate';
import type { PagedRecruitmentResultOfCandidateTotalCount } from './pagedRecruitmentResultOfCandidateTotalCount';
import type { PagedRecruitmentResultOfCandidatePage } from './pagedRecruitmentResultOfCandidatePage';
import type { PagedRecruitmentResultOfCandidatePageSize } from './pagedRecruitmentResultOfCandidatePageSize';

export interface PagedRecruitmentResultOfCandidate {
  items: Candidate[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: PagedRecruitmentResultOfCandidateTotalCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: PagedRecruitmentResultOfCandidatePage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: PagedRecruitmentResultOfCandidatePageSize;
}
