/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LeaveRequestDto } from './leaveRequestDto';
import type { PagedLeaveRequestsResponseTotalCount } from './pagedLeaveRequestsResponseTotalCount';
import type { PagedLeaveRequestsResponsePage } from './pagedLeaveRequestsResponsePage';
import type { PagedLeaveRequestsResponsePageSize } from './pagedLeaveRequestsResponsePageSize';

export interface PagedLeaveRequestsResponse {
  items: LeaveRequestDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: PagedLeaveRequestsResponseTotalCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page: PagedLeaveRequestsResponsePage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize: PagedLeaveRequestsResponsePageSize;
}
