/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LeaveRequestDto } from './leaveRequestDto';
import type { PagedSelfServiceLeaveRequestsResponseTotalCount } from './pagedSelfServiceLeaveRequestsResponseTotalCount';
import type { PagedSelfServiceLeaveRequestsResponsePage } from './pagedSelfServiceLeaveRequestsResponsePage';
import type { PagedSelfServiceLeaveRequestsResponsePageSize } from './pagedSelfServiceLeaveRequestsResponsePageSize';

export interface PagedSelfServiceLeaveRequestsResponse {
  items: LeaveRequestDto[];
  totalCount: PagedSelfServiceLeaveRequestsResponseTotalCount;
  page: PagedSelfServiceLeaveRequestsResponsePage;
  pageSize: PagedSelfServiceLeaveRequestsResponsePageSize;
}
