/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentInstructionDtoAmount } from './paymentInstructionDtoAmount';

export interface PaymentInstructionDto {
  id: string;
  employmentId: string;
  beneficiaryName: string;
  bankCode: string;
  accountMasked: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  amount: PaymentInstructionDtoAmount;
  status: string;
}
