/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PayrollInputSnapshotDtoBaseSalaryMonthly } from './payrollInputSnapshotDtoBaseSalaryMonthly';
import type { PayrollInputSnapshotDtoScheduledDays } from './payrollInputSnapshotDtoScheduledDays';
import type { PayrollInputSnapshotDtoVerifiedWorkedMinutes } from './payrollInputSnapshotDtoVerifiedWorkedMinutes';
import type { PayrollInputSnapshotDtoApprovedAbsenceDays } from './payrollInputSnapshotDtoApprovedAbsenceDays';
import type { PayrollInputSnapshotDtoApprovedLeaveDays } from './payrollInputSnapshotDtoApprovedLeaveDays';
import type { PayrollInputSnapshotDtoUnpaidLeaveDays } from './payrollInputSnapshotDtoUnpaidLeaveDays';

export interface PayrollInputSnapshotDto {
  employmentId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  baseSalaryMonthly: PayrollInputSnapshotDtoBaseSalaryMonthly;
  allowancesJson: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  scheduledDays: PayrollInputSnapshotDtoScheduledDays;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  verifiedWorkedMinutes: PayrollInputSnapshotDtoVerifiedWorkedMinutes;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  approvedAbsenceDays: PayrollInputSnapshotDtoApprovedAbsenceDays;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  approvedLeaveDays: PayrollInputSnapshotDtoApprovedLeaveDays;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  unpaidLeaveDays: PayrollInputSnapshotDtoUnpaidLeaveDays;
}
