/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PayrollEmployeeResultDetailDtoGrossPay } from './payrollEmployeeResultDetailDtoGrossPay';
import type { PayrollEmployeeResultDetailDtoNetPay } from './payrollEmployeeResultDetailDtoNetPay';
import type { PayrollEmployeeResultDetailDtoTotalEarnings } from './payrollEmployeeResultDetailDtoTotalEarnings';
import type { PayrollEmployeeResultDetailDtoTotalDeductions } from './payrollEmployeeResultDetailDtoTotalDeductions';
import type { PayrollEmployeeResultDetailDtoEmployerContributions } from './payrollEmployeeResultDetailDtoEmployerContributions';
import type { PayrollLineDto } from './payrollLineDto';
import type { CalculationTraceDto } from './calculationTraceDto';

export interface PayrollEmployeeResultDetailDto {
  id: string;
  payrollRunId: string;
  employmentId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  grossPay: PayrollEmployeeResultDetailDtoGrossPay;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  netPay: PayrollEmployeeResultDetailDtoNetPay;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  totalEarnings: PayrollEmployeeResultDetailDtoTotalEarnings;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  totalDeductions: PayrollEmployeeResultDetailDtoTotalDeductions;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  employerContributions: PayrollEmployeeResultDetailDtoEmployerContributions;
  lines: PayrollLineDto[];
  traces: CalculationTraceDto[];
}
