/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PayrollRunDtoTotalGross } from './payrollRunDtoTotalGross';
import type { PayrollRunDtoTotalNet } from './payrollRunDtoTotalNet';
import type { PayrollRunDtoTotalEmployerContributions } from './payrollRunDtoTotalEmployerContributions';
import type { PayrollRunDtoEmployeeCount } from './payrollRunDtoEmployeeCount';
import type { PayrollRunDtoFinalizedAtUtc } from './payrollRunDtoFinalizedAtUtc';
import type { PayrollRunDtoRowVersion } from './payrollRunDtoRowVersion';

export interface PayrollRunDto {
  id: string;
  periodId: string;
  code: string;
  status: string;
  currency: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  totalGross: PayrollRunDtoTotalGross;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  totalNet: PayrollRunDtoTotalNet;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  totalEmployerContributions: PayrollRunDtoTotalEmployerContributions;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  employeeCount: PayrollRunDtoEmployeeCount;
  reproducibilityHash: string;
  finalizedAtUtc: PayrollRunDtoFinalizedAtUtc;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: PayrollRunDtoRowVersion;
}
