/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PayrollExceptionDtoResolvedByUserId } from './payrollExceptionDtoResolvedByUserId';
import type { PayrollExceptionDtoResolutionNote } from './payrollExceptionDtoResolutionNote';

export interface PayrollExceptionDto {
  id: string;
  payrollRunId: string;
  employmentId: string;
  severity: string;
  category: string;
  reason: string;
  resolutionGuidance: string;
  status: string;
  resolvedByUserId: PayrollExceptionDtoResolvedByUserId;
  resolutionNote: PayrollExceptionDtoResolutionNote;
}
