/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PayrollEmployeeResultSummaryDtoGrossPay } from './payrollEmployeeResultSummaryDtoGrossPay';
import type { PayrollEmployeeResultSummaryDtoNetPay } from './payrollEmployeeResultSummaryDtoNetPay';
import type { PayrollEmployeeResultSummaryDtoTotalEarnings } from './payrollEmployeeResultSummaryDtoTotalEarnings';
import type { PayrollEmployeeResultSummaryDtoTotalDeductions } from './payrollEmployeeResultSummaryDtoTotalDeductions';
import type { PayrollEmployeeResultSummaryDtoEmployerContributions } from './payrollEmployeeResultSummaryDtoEmployerContributions';

export interface PayrollEmployeeResultSummaryDto {
  id: string;
  payrollRunId: string;
  employmentId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  grossPay: PayrollEmployeeResultSummaryDtoGrossPay;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  netPay: PayrollEmployeeResultSummaryDtoNetPay;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  totalEarnings: PayrollEmployeeResultSummaryDtoTotalEarnings;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  totalDeductions: PayrollEmployeeResultSummaryDtoTotalDeductions;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  employerContributions: PayrollEmployeeResultSummaryDtoEmployerContributions;
}
