/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PayrollLineDtoAmount } from './payrollLineDtoAmount';
import type { PayrollLineDtoRate } from './payrollLineDtoRate';
import type { PayrollLineDtoHoursOrDays } from './payrollLineDtoHoursOrDays';
import type { PayrollLineDtoTraceId } from './payrollLineDtoTraceId';

export interface PayrollLineDto {
  id: string;
  componentCode: string;
  nameEn: string;
  nameAr: string;
  category: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  amount: PayrollLineDtoAmount;
  calculationType: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  rate: PayrollLineDtoRate;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  hoursOrDays: PayrollLineDtoHoursOrDays;
  traceId: PayrollLineDtoTraceId;
}
