/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { PlatformSettingEffectiveEndDate } from './platformSettingEffectiveEndDate';
import type { PlatformSettingRowVersion } from './platformSettingRowVersion';

export interface PlatformSetting {
  id: string;
  tenantId: TenantId;
  category: string;
  key: string;
  valueJson: string;
  effectiveStartDate: string;
  effectiveEndDate: PlatformSettingEffectiveEndDate;
  isCurrent: boolean;
  changedByUserId: string;
  changedAtUtc: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: PlatformSettingRowVersion;
}
