/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { IFormFile } from './iFormFile';

export type PostApiV1DocumentsUploadBody = {
  OwnerType?: string;
  OwnerId?: string;
  DocumentTypeId?: string;
  Title?: string;
  ExpiryDate?: string;
  File?: IFormFile;
};
