/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { QueueExportRequestFilters } from './queueExportRequestFilters';
import type { QueueExportRequestIdempotencyKey } from './queueExportRequestIdempotencyKey';

export interface QueueExportRequest {
  filters?: QueueExportRequestFilters;
  outputFormat?: string;
  idempotencyKey?: QueueExportRequestIdempotencyKey;
}
