/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ClockType } from './clockType';
import type { ClockSource } from './clockSource';
import type { RecordClockRequestCapturedAtUtc } from './recordClockRequestCapturedAtUtc';
import type { RecordClockRequestSourceDeviceId } from './recordClockRequestSourceDeviceId';
import type { RecordClockRequestLatitude } from './recordClockRequestLatitude';
import type { RecordClockRequestLongitude } from './recordClockRequestLongitude';

export interface RecordClockRequest {
  employmentId: string;
  type: ClockType;
  source: ClockSource;
  capturedAtUtc?: RecordClockRequestCapturedAtUtc;
  sourceDeviceId?: RecordClockRequestSourceDeviceId;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  latitude?: RecordClockRequestLatitude;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?$ */
  longitude?: RecordClockRequestLongitude;
}
