/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RecruitmentStageStageOrder } from './recruitmentStageStageOrder';
import type { StageKind } from './stageKind';

export interface RecruitmentStage {
  id: string;
  pipelineVersionId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  stageOrder: RecruitmentStageStageOrder;
  code: string;
  nameEn: string;
  nameAr: string;
  stageKind: StageKind;
}
