/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RecruitmentPipelineVersionVersionNumber } from './recruitmentPipelineVersionVersionNumber';
import type { RecruitmentPipelineVersionStages } from './recruitmentPipelineVersionStages';

export interface RecruitmentPipelineVersion {
  id: string;
  pipelineId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  versionNumber: RecruitmentPipelineVersionVersionNumber;
  isImmutable?: boolean;
  createdAtUtc?: string;
  stages?: RecruitmentPipelineVersionStages;
}
