/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { RecruitmentPipelineRowVersion } from './recruitmentPipelineRowVersion';
import type { RecruitmentPipelineVersions } from './recruitmentPipelineVersions';

export interface RecruitmentPipeline {
  id: string;
  tenantId: TenantId;
  code: string;
  nameEn: string;
  nameAr: string;
  isActive?: boolean;
  createdAtUtc?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: RecruitmentPipelineRowVersion;
  versions?: RecruitmentPipelineVersions;
}
