/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RejectApplicationRequestReasonNote } from './rejectApplicationRequestReasonNote';
import type { RejectApplicationRequestExpectedRowVersion } from './rejectApplicationRequestExpectedRowVersion';

export interface RejectApplicationRequest {
  reasonCode: string;
  reasonNote: RejectApplicationRequestReasonNote;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: RejectApplicationRequestExpectedRowVersion;
}
