/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ReportExecutionMode } from './reportExecutionMode';
import type { ReportDefinitionVersion } from './reportDefinitionVersion';

export interface ReportDefinition {
  reportCode: string;
  nameEn: string;
  nameAr: string;
  domain: string;
  descriptionEn: string;
  descriptionAr: string;
  allowedFiltersJson: string;
  allowedColumnsJson: string;
  requiredPermissionsJson: string;
  dataClassification?: string;
  supportedFormatsJson?: string;
  executionMode?: ReportExecutionMode;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  version?: ReportDefinitionVersion;
}
