/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ReportExecutionDataRowsItem } from './reportExecutionDataRowsItem';
import type { ReportExecutionDataTotalCount } from './reportExecutionDataTotalCount';

export interface ReportExecutionData {
  columns: string[];
  rows: ReportExecutionDataRowsItem[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: ReportExecutionDataTotalCount;
}
