/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { ReportExecutionJobLegalEntityId } from './reportExecutionJobLegalEntityId';
import type { ReportJobStatus } from './reportJobStatus';
import type { ReportExecutionJobCompletedAtUtc } from './reportExecutionJobCompletedAtUtc';
import type { ReportExecutionJobStorageKey } from './reportExecutionJobStorageKey';
import type { ReportExecutionJobFileSizeBytes } from './reportExecutionJobFileSizeBytes';
import type { ReportExecutionJobSha256Checksum } from './reportExecutionJobSha256Checksum';
import type { ReportExecutionJobErrorMessage } from './reportExecutionJobErrorMessage';
import type { ReportExecutionJobRowCount } from './reportExecutionJobRowCount';
import type { ReportExecutionJobIdempotencyKey } from './reportExecutionJobIdempotencyKey';

export interface ReportExecutionJob {
  id: string;
  tenantId: TenantId;
  legalEntityId: ReportExecutionJobLegalEntityId;
  reportCode: string;
  status?: ReportJobStatus;
  requestedByUserId: string;
  requestedAtUtc?: string;
  completedAtUtc?: ReportExecutionJobCompletedAtUtc;
  filtersJson?: string;
  outputFormat?: string;
  storageKey?: ReportExecutionJobStorageKey;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  fileSizeBytes?: ReportExecutionJobFileSizeBytes;
  sha256Checksum?: ReportExecutionJobSha256Checksum;
  errorMessage?: ReportExecutionJobErrorMessage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowCount?: ReportExecutionJobRowCount;
  idempotencyKey?: ReportExecutionJobIdempotencyKey;
}
