/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RescheduleInterviewRequestLocationOrMeetingUrl } from './rescheduleInterviewRequestLocationOrMeetingUrl';
import type { RescheduleInterviewRequestExpectedRowVersion } from './rescheduleInterviewRequestExpectedRowVersion';

export interface RescheduleInterviewRequest {
  newStartUtc: string;
  newEndUtc: string;
  timezone: string;
  locationOrMeetingUrl: RescheduleInterviewRequestLocationOrMeetingUrl;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: RescheduleInterviewRequestExpectedRowVersion;
}
