/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { RetentionPolicyRetentionDays } from './retentionPolicyRetentionDays';
import type { ExpiryAction } from './expiryAction';
import type { RetentionPolicyRowVersion } from './retentionPolicyRowVersion';

export interface RetentionPolicy {
  id: string;
  tenantId: TenantId;
  module: string;
  dataCategory: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  retentionDays: RetentionPolicyRetentionDays;
  actionOnExpiry: ExpiryAction;
  isActive: boolean;
  effectiveStartDate: string;
  changedByUserId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: RetentionPolicyRowVersion;
}
