/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { RoleRowVersion } from './roleRowVersion';

export interface Role {
  id: string;
  tenantId: TenantId;
  code: string;
  nameEn: string;
  nameAr: string;
  description: string;
  permissionsJson: string;
  isSystemRole?: boolean;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: RoleRowVersion;
}
