/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { RoleAssignmentLegalEntityScopeId } from './roleAssignmentLegalEntityScopeId';
import type { RoleAssignmentOrganizationUnitScopeId } from './roleAssignmentOrganizationUnitScopeId';

export interface RoleAssignment {
  id: string;
  tenantId: TenantId;
  userId: string;
  roleId: string;
  legalEntityScopeId: RoleAssignmentLegalEntityScopeId;
  organizationUnitScopeId: RoleAssignmentOrganizationUnitScopeId;
  assignedByUserId: string;
  assignedAtUtc: string;
}
