/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RunReportRequestFilters } from './runReportRequestFilters';
import type { RunReportRequestPage } from './runReportRequestPage';
import type { RunReportRequestPageSize } from './runReportRequestPageSize';

export interface RunReportRequest {
  filters?: RunReportRequestFilters;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  page?: RunReportRequestPage;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: RunReportRequestPageSize;
}
