/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RunReportRequestFiltersAnyOf } from './runReportRequestFiltersAnyOf';

export type RunReportRequestFilters = null | RunReportRequestFiltersAnyOf;
