/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SaveSettingRequestEffectiveEndDate } from './saveSettingRequestEffectiveEndDate';

export interface SaveSettingRequest {
  category: string;
  key: string;
  valueJson: string;
  effectiveStartDate: string;
  effectiveEndDate: SaveSettingRequestEffectiveEndDate;
}
