/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SaveRetentionPolicyRequestRetentionDays } from './saveRetentionPolicyRequestRetentionDays';
import type { ExpiryAction } from './expiryAction';

export interface SaveRetentionPolicyRequest {
  module: string;
  dataCategory: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  retentionDays: SaveRetentionPolicyRequestRetentionDays;
  actionOnExpiry: ExpiryAction;
  isActive: boolean;
  effectiveStartDate: string;
}
