/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { SavedReportViewLegalEntityId } from './savedReportViewLegalEntityId';

export interface SavedReportView {
  id: string;
  tenantId: TenantId;
  legalEntityId: SavedReportViewLegalEntityId;
  reportCode: string;
  viewName: string;
  isTenantShared: boolean;
  ownerUserId: string;
  filtersJson?: string;
  columnsJson?: string;
  sortJson?: string;
  groupingJson?: string;
  createdAtUtc?: string;
}
