/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { InterviewType } from './interviewType';
import type { ScheduleInterviewRequestLocationOrMeetingUrl } from './scheduleInterviewRequestLocationOrMeetingUrl';
import type { ScheduleInterviewRequestInterviewKitJson } from './scheduleInterviewRequestInterviewKitJson';
import type { ScheduleInterviewRequestParticipants } from './scheduleInterviewRequestParticipants';

export interface ScheduleInterviewRequest {
  applicationId: string;
  stageId: string;
  title: string;
  interviewType: InterviewType;
  scheduledStartUtc: string;
  scheduledEndUtc: string;
  timezone: string;
  locationOrMeetingUrl: ScheduleInterviewRequestLocationOrMeetingUrl;
  interviewKitJson: ScheduleInterviewRequestInterviewKitJson;
  participants: ScheduleInterviewRequestParticipants;
}
