/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ScorecardSubmissionStrengths } from './scorecardSubmissionStrengths';
import type { ScorecardSubmissionConcerns } from './scorecardSubmissionConcerns';
import type { ScorecardRecommendation } from './scorecardRecommendation';
import type { ScorecardSubmissionRowVersion } from './scorecardSubmissionRowVersion';

export interface ScorecardSubmission {
  id: string;
  interviewId: string;
  applicationId: string;
  interviewerUserId: string;
  ratingsJson: string;
  strengths: ScorecardSubmissionStrengths;
  concerns: ScorecardSubmissionConcerns;
  recommendation: ScorecardRecommendation;
  isFinalized?: boolean;
  submittedAtUtc?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: ScorecardSubmissionRowVersion;
}
