/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SelfServiceLeaveRequestResponseRowVersion } from './selfServiceLeaveRequestResponseRowVersion';

export interface SelfServiceLeaveRequestResponse {
  requestId: string;
  approvalRequestId: string;
  status: string;
  rowVersion: SelfServiceLeaveRequestResponseRowVersion;
}
