/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ClockType } from './clockType';
import type { ClockSource } from './clockSource';
import type { SelfServiceClockRequestSourceDeviceId } from './selfServiceClockRequestSourceDeviceId';
import type { SelfServiceClockRequestLatitude } from './selfServiceClockRequestLatitude';
import type { SelfServiceClockRequestLongitude } from './selfServiceClockRequestLongitude';

export interface SelfServiceClockRequest {
  type: ClockType;
  source?: ClockSource;
  sourceDeviceId?: SelfServiceClockRequestSourceDeviceId;
  latitude?: SelfServiceClockRequestLatitude;
  longitude?: SelfServiceClockRequestLongitude;
}
