/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SelfServiceProfileUpdateRequestPrimaryEmail } from './selfServiceProfileUpdateRequestPrimaryEmail';
import type { SelfServiceProfileUpdateRequestPhoneNumber } from './selfServiceProfileUpdateRequestPhoneNumber';
import type { SelfServiceProfileUpdateRequestRowVersion } from './selfServiceProfileUpdateRequestRowVersion';

export interface SelfServiceProfileUpdateRequest {
  primaryEmail?: SelfServiceProfileUpdateRequestPrimaryEmail;
  phoneNumber?: SelfServiceProfileUpdateRequestPhoneNumber;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: SelfServiceProfileUpdateRequestRowVersion;
}
