/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SelfServiceLeaveRequestInputAttachmentDocumentId } from './selfServiceLeaveRequestInputAttachmentDocumentId';

export interface SelfServiceLeaveRequestInput {
  leaveTypeId: string;
  startDate: string;
  endDate: string;
  reason: string;
  attachmentDocumentId?: SelfServiceLeaveRequestInputAttachmentDocumentId;
}
