/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SensitiveRevealResponseExpirySeconds } from './sensitiveRevealResponseExpirySeconds';

export interface SensitiveRevealResponse {
  fieldName?: string;
  plaintextValue?: string;
  revealedAt?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expirySeconds?: SensitiveRevealResponseExpirySeconds;
}
