/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SettlementBatchDtoTotalAmount } from './settlementBatchDtoTotalAmount';
import type { SettlementBatchDtoInstructionCount } from './settlementBatchDtoInstructionCount';
import type { SettlementBatchDtoRowVersion } from './settlementBatchDtoRowVersion';

export interface SettlementBatchDto {
  id: string;
  payrollRunId: string;
  batchNumber: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  totalAmount: SettlementBatchDtoTotalAmount;
  currency: string;
  paymentDate: string;
  status: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  instructionCount: SettlementBatchDtoInstructionCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: SettlementBatchDtoRowVersion;
}
