/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SettlementBatchDetailDtoTotalAmount } from './settlementBatchDetailDtoTotalAmount';
import type { SettlementBatchDetailDtoRowVersion } from './settlementBatchDetailDtoRowVersion';
import type { PaymentInstructionDto } from './paymentInstructionDto';

export interface SettlementBatchDetailDto {
  id: string;
  payrollRunId: string;
  batchNumber: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  totalAmount: SettlementBatchDetailDtoTotalAmount;
  currency: string;
  paymentDate: string;
  status: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: SettlementBatchDetailDtoRowVersion;
  instructions: PaymentInstructionDto[];
}
