/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SourceReferenceDtoEntityType } from './sourceReferenceDtoEntityType';
import type { SourceReferenceDtoEntityId } from './sourceReferenceDtoEntityId';
import type { SourceReferenceDtoPolicyCode } from './sourceReferenceDtoPolicyCode';
import type { SourceReferenceDtoPolicyVersion } from './sourceReferenceDtoPolicyVersion';
import type { SourceReferenceDtoPayrollRunId } from './sourceReferenceDtoPayrollRunId';

export interface SourceReferenceDto {
  id: string;
  sourceCategory: string;
  title: string;
  entityType: SourceReferenceDtoEntityType;
  entityId: SourceReferenceDtoEntityId;
  policyCode: SourceReferenceDtoPolicyCode;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  policyVersion: SourceReferenceDtoPolicyVersion;
  payrollRunId: SourceReferenceDtoPayrollRunId;
  metadataJson: string;
  retrievedAtUtc: string;
}
