/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface StatutoryRuleDto {
  code: string;
  nameEn: string;
  nameAr: string;
  jurisdiction: string;
  category: string;
  sourceReferenceLaw: string;
  isVerified: boolean;
}
