/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SubmitScorecardRequestStrengths } from './submitScorecardRequestStrengths';
import type { SubmitScorecardRequestConcerns } from './submitScorecardRequestConcerns';
import type { ScorecardRecommendation } from './scorecardRecommendation';
import type { SubmitScorecardRequestExpectedRowVersion } from './submitScorecardRequestExpectedRowVersion';

export interface SubmitScorecardRequest {
  ratingsJson: string;
  strengths: SubmitScorecardRequestStrengths;
  concerns: SubmitScorecardRequestConcerns;
  recommendation: ScorecardRecommendation;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: SubmitScorecardRequestExpectedRowVersion;
}
