/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SubmitAdjustmentRequestAdjustedWorkedMinutes } from './submitAdjustmentRequestAdjustedWorkedMinutes';
import type { SubmitAdjustmentRequestRowVersion } from './submitAdjustmentRequestRowVersion';
import type { SubmitAdjustmentRequestApprovalRequestId } from './submitAdjustmentRequestApprovalRequestId';

export interface SubmitAdjustmentRequest {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  adjustedWorkedMinutes: SubmitAdjustmentRequestAdjustedWorkedMinutes;
  reason: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: SubmitAdjustmentRequestRowVersion;
  approvalRequestId?: SubmitAdjustmentRequestApprovalRequestId;
}
