/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantDto } from './tenantDto';
import type { LegalEntityDto } from './legalEntityDto';
import type { TenantContextDtoActiveLegalEntityId } from './tenantContextDtoActiveLegalEntityId';

export interface TenantContextDto {
  tenant: TenantDto;
  legalEntities: LegalEntityDto[];
  activeLegalEntityId: TenantContextDtoActiveLegalEntityId;
}
