/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ToolExecutionDtoDurationMs } from './toolExecutionDtoDurationMs';

export interface ToolExecutionDto {
  id: string;
  toolCode: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  durationMs: ToolExecutionDtoDurationMs;
  status: string;
  createdAtUtc: string;
}
