/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCandidateRequestLocation } from './updateCandidateRequestLocation';
import type { UpdateCandidateRequestHeadline } from './updateCandidateRequestHeadline';
import type { UpdateCandidateRequestSource } from './updateCandidateRequestSource';
import type { UpdateCandidateRequestResumeDocumentId } from './updateCandidateRequestResumeDocumentId';
import type { UpdateCandidateRequestSkillsJson } from './updateCandidateRequestSkillsJson';
import type { UpdateCandidateRequestExpectedRowVersion } from './updateCandidateRequestExpectedRowVersion';

export interface UpdateCandidateRequest {
  firstNameEn: string;
  lastNameEn: string;
  firstNameAr: string;
  lastNameAr: string;
  email: string;
  phoneNumber: string;
  location: UpdateCandidateRequestLocation;
  headline: UpdateCandidateRequestHeadline;
  source: UpdateCandidateRequestSource;
  resumeDocumentId: UpdateCandidateRequestResumeDocumentId;
  skillsJson: UpdateCandidateRequestSkillsJson;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: UpdateCandidateRequestExpectedRowVersion;
}
