/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { IntegrationAuthType } from './integrationAuthType';
import type { UpdateConnectorRequestSecretCredential } from './updateConnectorRequestSecretCredential';
import type { UpdateConnectorRequestExpectedRowVersion } from './updateConnectorRequestExpectedRowVersion';

export interface UpdateConnectorRequest {
  nameEn: string;
  nameAr: string;
  endpointUrl: string;
  authType: IntegrationAuthType;
  secretCredential: UpdateConnectorRequestSecretCredential;
  isActive: boolean;
  eventSubscriptionsJson: string;
  configJson: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: UpdateConnectorRequestExpectedRowVersion;
}
