/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateRequisitionRequestPositionId } from './updateRequisitionRequestPositionId';
import type { UpdateRequisitionRequestLocationId } from './updateRequisitionRequestLocationId';
import type { UpdateRequisitionRequestOpeningsCount } from './updateRequisitionRequestOpeningsCount';
import type { UpdateRequisitionRequestRequisitionReason } from './updateRequisitionRequestRequisitionReason';
import type { UpdateRequisitionRequestTargetStartDate } from './updateRequisitionRequestTargetStartDate';
import type { UpdateRequisitionRequestExpectedRowVersion } from './updateRequisitionRequestExpectedRowVersion';

export interface UpdateRequisitionRequest {
  organizationUnitId: string;
  positionId: UpdateRequisitionRequestPositionId;
  locationId: UpdateRequisitionRequestLocationId;
  hiringManagerId: string;
  recruiterId: string;
  titleEn: string;
  titleAr: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  openingsCount: UpdateRequisitionRequestOpeningsCount;
  employmentType: string;
  requisitionReason: UpdateRequisitionRequestRequisitionReason;
  targetStartDate: UpdateRequisitionRequestTargetStartDate;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: UpdateRequisitionRequestExpectedRowVersion;
}
