/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOrganizationUnitRequestParentUnitId } from './updateOrganizationUnitRequestParentUnitId';
import type { UpdateOrganizationUnitRequestManagerPositionId } from './updateOrganizationUnitRequestManagerPositionId';
import type { UpdateOrganizationUnitRequestEffectiveTo } from './updateOrganizationUnitRequestEffectiveTo';
import type { UpdateOrganizationUnitRequestRowVersion } from './updateOrganizationUnitRequestRowVersion';

export interface UpdateOrganizationUnitRequest {
  nameEn?: string;
  nameAr?: string;
  type?: string;
  parentUnitId?: UpdateOrganizationUnitRequestParentUnitId;
  managerPositionId?: UpdateOrganizationUnitRequestManagerPositionId;
  effectiveFrom?: string;
  effectiveTo?: UpdateOrganizationUnitRequestEffectiveTo;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: UpdateOrganizationUnitRequestRowVersion;
}
