/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateLegalEntityRequestRowVersion } from './updateLegalEntityRequestRowVersion';

export interface UpdateLegalEntityRequest {
  nameEn: string;
  nameAr: string;
  countryCode: string;
  currencyCode: string;
  timezoneId: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion: UpdateLegalEntityRequestRowVersion;
}
