/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateRoleRequestExpectedVersion } from './updateRoleRequestExpectedVersion';

export interface UpdateRoleRequest {
  nameEn: string;
  nameAr: string;
  description: string;
  permissions: string[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedVersion: UpdateRoleRequestExpectedVersion;
}
