/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOfferTermsRequestBaseSalaryMonthly } from './updateOfferTermsRequestBaseSalaryMonthly';
import type { UpdateOfferTermsRequestAllowancesJson } from './updateOfferTermsRequestAllowancesJson';
import type { UpdateOfferTermsRequestConditionsNote } from './updateOfferTermsRequestConditionsNote';
import type { UpdateOfferTermsRequestExpiryDate } from './updateOfferTermsRequestExpiryDate';
import type { UpdateOfferTermsRequestOfferDocumentId } from './updateOfferTermsRequestOfferDocumentId';
import type { UpdateOfferTermsRequestExpectedRowVersion } from './updateOfferTermsRequestExpectedRowVersion';

export interface UpdateOfferTermsRequest {
  titleEn: string;
  titleAr: string;
  proposedStartDate: string;
  /** @pattern ^-?(?:0|[1-9]\d*)(?:\.\d+)?$ */
  baseSalaryMonthly: UpdateOfferTermsRequestBaseSalaryMonthly;
  currency: string;
  allowancesJson: UpdateOfferTermsRequestAllowancesJson;
  conditionsNote: UpdateOfferTermsRequestConditionsNote;
  expiryDate: UpdateOfferTermsRequestExpiryDate;
  offerDocumentId: UpdateOfferTermsRequestOfferDocumentId;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: UpdateOfferTermsRequestExpectedRowVersion;
}
