/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { WithdrawApplicationRequestReason } from './withdrawApplicationRequestReason';
import type { WithdrawApplicationRequestExpectedRowVersion } from './withdrawApplicationRequestExpectedRowVersion';

export interface WithdrawApplicationRequest {
  reason: WithdrawApplicationRequestReason;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expectedRowVersion: WithdrawApplicationRequestExpectedRowVersion;
}
