/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantId } from './tenantId';
import type { LegalEntityId } from './legalEntityId';
import type { WorkScheduleGracePeriodMinutes } from './workScheduleGracePeriodMinutes';
import type { EffectivePeriod } from './effectivePeriod';

export interface WorkSchedule {
  id: string;
  tenantId: TenantId;
  legalEntityId: LegalEntityId;
  code: string;
  nameEn: string;
  nameAr: string;
  shiftStartTime: string;
  shiftEndTime: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  gracePeriodMinutes: WorkScheduleGracePeriodMinutes;
  timeZoneId: string;
  crossesMidnight?: boolean;
  effectivePeriod: EffectivePeriod;
  isActive?: boolean;
}
