/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
export type ChangeAssignmentRequestPositionId = null | string;

export type ChangeAssignmentRequestLocationId = null | string;

export type ChangeAssignmentRequestManagerEmploymentId = null | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type ChangeAssignmentRequestRowVersion = number | string;

export interface ChangeAssignmentRequest {
  organizationUnitId?: string;
  positionId?: ChangeAssignmentRequestPositionId;
  locationId?: ChangeAssignmentRequestLocationId;
  managerEmploymentId?: ChangeAssignmentRequestManagerEmploymentId;
  jobTitleEn?: string;
  jobTitleAr?: string;
  effectiveFrom?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: ChangeAssignmentRequestRowVersion;
}

export type ChangeContextRequestLegalEntityId = null | string;

export interface ChangeContextRequest {
  tenantId: string;
  legalEntityId: ChangeContextRequestLegalEntityId;
}

export type CreateEmployeeRequestLegalEntityId = null | string;

export type CreateEmployeeRequestEmployeeNumber = null | string;

export type CreateEmployeeRequestGender = null | string;

export type CreateEmployeeRequestNationality = null | string;

export type CreateEmployeeRequestPrimaryEmail = null | string;

export type CreateEmployeeRequestPhoneNumber = null | string;

export type CreateEmployeeRequestPositionId = null | string;

export type CreateEmployeeRequestLocationId = null | string;

export type CreateEmployeeRequestManagerEmploymentId = null | string;

export interface CreateEmployeeRequest {
  legalEntityId?: CreateEmployeeRequestLegalEntityId;
  employeeNumber?: CreateEmployeeRequestEmployeeNumber;
  firstNameEn?: string;
  lastNameEn?: string;
  firstNameAr?: string;
  lastNameAr?: string;
  dateOfBirth?: string;
  gender?: CreateEmployeeRequestGender;
  nationality?: CreateEmployeeRequestNationality;
  nationalIdentifier?: string;
  primaryEmail?: CreateEmployeeRequestPrimaryEmail;
  phoneNumber?: CreateEmployeeRequestPhoneNumber;
  hireDate?: string;
  organizationUnitId?: string;
  positionId?: CreateEmployeeRequestPositionId;
  locationId?: CreateEmployeeRequestLocationId;
  managerEmploymentId?: CreateEmployeeRequestManagerEmploymentId;
  jobTitleEn?: string;
  jobTitleAr?: string;
}

export type CreateLocationRequestCountry = null | string;

export type CreateLocationRequestCity = null | string;

export type CreateLocationRequestAddress = null | string;

export interface CreateLocationRequest {
  code?: string;
  nameEn?: string;
  nameAr?: string;
  country?: CreateLocationRequestCountry;
  city?: CreateLocationRequestCity;
  address?: CreateLocationRequestAddress;
}

export type CreateOrganizationUnitRequestLegalEntityId = null | string;

export type CreateOrganizationUnitRequestParentUnitId = null | string;

export type CreateOrganizationUnitRequestManagerPositionId = null | string;

export type CreateOrganizationUnitRequestEffectiveTo = null | string;

export interface CreateOrganizationUnitRequest {
  legalEntityId?: CreateOrganizationUnitRequestLegalEntityId;
  code?: string;
  nameEn?: string;
  nameAr?: string;
  type?: string;
  parentUnitId?: CreateOrganizationUnitRequestParentUnitId;
  managerPositionId?: CreateOrganizationUnitRequestManagerPositionId;
  effectiveFrom?: string;
  effectiveTo?: CreateOrganizationUnitRequestEffectiveTo;
}

export type DocumentDetailDtoExpiryDate = null | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type DocumentDetailDtoLatestVersionNumber = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type DocumentDetailDtoLatestFileSize = number | string;

export interface DocumentDetailDto {
  versions?: DocumentVersionDto[];
  id?: string;
  tenantId?: string;
  legalEntityId?: string;
  ownerType?: string;
  ownerId?: string;
  documentTypeId?: string;
  documentTypeCode?: string;
  documentTypeNameEn?: string;
  documentTypeNameAr?: string;
  title?: string;
  status?: string;
  expiryDate?: DocumentDetailDtoExpiryDate;
  createdAt?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  latestVersionNumber?: DocumentDetailDtoLatestVersionNumber;
  latestFileName?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  latestFileSize?: DocumentDetailDtoLatestFileSize;
  latestContentType?: string;
}

export type DocumentSummaryDtoExpiryDate = null | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type DocumentSummaryDtoLatestVersionNumber = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type DocumentSummaryDtoLatestFileSize = number | string;

export interface DocumentSummaryDto {
  id?: string;
  tenantId?: string;
  legalEntityId?: string;
  ownerType?: string;
  ownerId?: string;
  documentTypeId?: string;
  documentTypeCode?: string;
  documentTypeNameEn?: string;
  documentTypeNameAr?: string;
  title?: string;
  status?: string;
  expiryDate?: DocumentSummaryDtoExpiryDate;
  createdAt?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  latestVersionNumber?: DocumentSummaryDtoLatestVersionNumber;
  latestFileName?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  latestFileSize?: DocumentSummaryDtoLatestFileSize;
  latestContentType?: string;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type DocumentTypeDtoMaxSizeBytes = number | string;

export interface DocumentTypeDto {
  id?: string;
  code?: string;
  nameEn?: string;
  nameAr?: string;
  isRequired?: boolean;
  requiresExpiryDate?: boolean;
  allowedMimeTypes?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  maxSizeBytes?: DocumentTypeDtoMaxSizeBytes;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type DocumentVersionDtoVersionNumber = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type DocumentVersionDtoFileSize = number | string;

export interface DocumentVersionDto {
  id?: string;
  documentId?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  versionNumber?: DocumentVersionDtoVersionNumber;
  fileName?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  fileSize?: DocumentVersionDtoFileSize;
  contentType?: string;
  sha256Checksum?: string;
  uploadedAt?: string;
  uploadedBy?: string;
}

export type EmployeeAssignmentDtoPositionId = null | string;

export type EmployeeAssignmentDtoLocationId = null | string;

export type EmployeeAssignmentDtoManagerEmploymentId = null | string;

export type EmployeeAssignmentDtoManagerNameEn = null | string;

export type EmployeeAssignmentDtoEffectiveTo = null | string;

export interface EmployeeAssignmentDto {
  id?: string;
  employmentId?: string;
  organizationUnitId?: string;
  departmentNameEn?: string;
  departmentNameAr?: string;
  positionId?: EmployeeAssignmentDtoPositionId;
  locationId?: EmployeeAssignmentDtoLocationId;
  locationNameEn?: string;
  managerEmploymentId?: EmployeeAssignmentDtoManagerEmploymentId;
  managerNameEn?: EmployeeAssignmentDtoManagerNameEn;
  jobTitleEn?: string;
  jobTitleAr?: string;
  effectiveFrom?: string;
  effectiveTo?: EmployeeAssignmentDtoEffectiveTo;
  isCurrent?: boolean;
}

export type EmployeeProfileDtoProbationEndDate = null | string;

export type EmployeeProfileDtoTerminationDate = null | string;

export type EmployeeProfileDtoTerminationReason = null | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type EmployeeProfileDtoRowVersion = number | string;

export type EmployeeProfileDtoCurrentAssignment = null | EmployeeAssignmentDto;

export interface EmployeeProfileDto {
  id?: string;
  personId?: string;
  tenantId?: string;
  legalEntityId?: string;
  employeeNumber?: string;
  firstNameEn?: string;
  lastNameEn?: string;
  firstNameAr?: string;
  lastNameAr?: string;
  fullNameEn?: string;
  fullNameAr?: string;
  gender?: string;
  nationality?: string;
  maskedDateOfBirth?: string;
  maskedNationalId?: string;
  primaryEmail?: string;
  phoneNumber?: string;
  status?: string;
  hireDate?: string;
  probationEndDate?: EmployeeProfileDtoProbationEndDate;
  terminationDate?: EmployeeProfileDtoTerminationDate;
  terminationReason?: EmployeeProfileDtoTerminationReason;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: EmployeeProfileDtoRowVersion;
  currentAssignment?: EmployeeProfileDtoCurrentAssignment;
  assignmentHistory?: EmployeeAssignmentDto[];
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type EmployeeSummaryDtoRowVersion = number | string;

export interface EmployeeSummaryDto {
  id?: string;
  tenantId?: string;
  legalEntityId?: string;
  employeeNumber?: string;
  firstNameEn?: string;
  lastNameEn?: string;
  firstNameAr?: string;
  lastNameAr?: string;
  fullNameEn?: string;
  fullNameAr?: string;
  primaryEmail?: string;
  phoneNumber?: string;
  departmentNameEn?: string;
  departmentNameAr?: string;
  jobTitleEn?: string;
  jobTitleAr?: string;
  locationNameEn?: string;
  status?: string;
  hireDate?: string;
  maskedNationalId?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: EmployeeSummaryDtoRowVersion;
}

export type IFormFile = Blob;

export interface LocationDto {
  id?: string;
  tenantId?: string;
  legalEntityId?: string;
  code?: string;
  nameEn?: string;
  nameAr?: string;
  country?: string;
  city?: string;
  address?: string;
  isActive?: boolean;
}

export type OrganizationUnitDtoParentUnitId = null | string;

export type OrganizationUnitDtoParentNameEn = null | string;

export type OrganizationUnitDtoManagerPositionId = null | string;

export type OrganizationUnitDtoEffectiveTo = null | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type OrganizationUnitDtoRowVersion = number | string;

export interface OrganizationUnitDto {
  id?: string;
  tenantId?: string;
  legalEntityId?: string;
  code?: string;
  nameEn?: string;
  nameAr?: string;
  type?: string;
  parentUnitId?: OrganizationUnitDtoParentUnitId;
  parentNameEn?: OrganizationUnitDtoParentNameEn;
  managerPositionId?: OrganizationUnitDtoManagerPositionId;
  isActive?: boolean;
  effectiveFrom?: string;
  effectiveTo?: OrganizationUnitDtoEffectiveTo;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: OrganizationUnitDtoRowVersion;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type PagedResultOfEmployeeSummaryDtoTotalCount = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type PagedResultOfEmployeeSummaryDtoPageNumber = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type PagedResultOfEmployeeSummaryDtoPageSize = number | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type PagedResultOfEmployeeSummaryDtoTotalPages = number | string;

export interface PagedResultOfEmployeeSummaryDto {
  items?: EmployeeSummaryDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: PagedResultOfEmployeeSummaryDtoTotalCount;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageNumber?: PagedResultOfEmployeeSummaryDtoPageNumber;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: PagedResultOfEmployeeSummaryDtoPageSize;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalPages?: PagedResultOfEmployeeSummaryDtoTotalPages;
}

export type ProblemDetailsType = null | string;

export type ProblemDetailsTitle = null | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type ProblemDetailsStatus = null | number | string;

export type ProblemDetailsDetail = null | string;

export type ProblemDetailsInstance = null | string;

export interface ProblemDetails {
  type?: ProblemDetailsType;
  title?: ProblemDetailsTitle;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  status?: ProblemDetailsStatus;
  detail?: ProblemDetailsDetail;
  instance?: ProblemDetailsInstance;
}

export interface RevealSensitiveFieldRequest {
  fieldName?: string;
  purpose?: string;
}

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type SensitiveRevealResponseExpirySeconds = number | string;

export interface SensitiveRevealResponse {
  fieldName?: string;
  plaintextValue?: string;
  revealedAt?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  expirySeconds?: SensitiveRevealResponseExpirySeconds;
}

export type UpdateOrganizationUnitRequestParentUnitId = null | string;

export type UpdateOrganizationUnitRequestManagerPositionId = null | string;

export type UpdateOrganizationUnitRequestEffectiveTo = null | string;

/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
export type UpdateOrganizationUnitRequestRowVersion = number | string;

export interface UpdateOrganizationUnitRequest {
  nameEn?: string;
  nameAr?: string;
  type?: string;
  parentUnitId?: UpdateOrganizationUnitRequestParentUnitId;
  managerPositionId?: UpdateOrganizationUnitRequestManagerPositionId;
  effectiveFrom?: string;
  effectiveTo?: UpdateOrganizationUnitRequestEffectiveTo;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  rowVersion?: UpdateOrganizationUnitRequestRowVersion;
}

export type GetApiV1DocumentsParams = {
ownerType?: string;
ownerId?: string;
};

export type GetApiV1DocumentsIdDownloadParams = {
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
version?: number | string;
};

export type PostApiV1DocumentsUploadBody = {
  OwnerType?: string;
  OwnerId?: string;
  DocumentTypeId?: string;
  Title?: string;
  ExpiryDate?: string;
  File?: IFormFile;
};

export type PostApiV1DocumentsIdVersionsBody = {
  File?: IFormFile;
};

export type GetApiV1OrganizationUnitsParams = {
legalEntityId?: string;
};

export type GetApiV1PeopleEmployeesParams = {
  search?: string;
  departmentId?: string;
  status?: string;
  /**
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  page?: number | string;
  /**
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  pageSize?: number | string;
};

// ==========================================
// Phase 3 — Attendance Module Contracts
// ==========================================

export enum ClockType {
  In = 0,
  Out = 1,
  BreakStart = 2,
  BreakEnd = 3
}

export enum ClockSource {
  WebPortal = 0,
  MobileApp = 1,
  BiometricDevice = 2,
  Kiosk = 3,
  SystemGenerated = 4
}

export enum AttendanceStatus {
  Unreviewed = 0,
  Reviewed = 1,
  Approved = 2,
  Locked = 3
}

export enum AttendanceExceptionType {
  MissingClockIn = 0,
  MissingClockOut = 1,
  LateArrival = 2,
  EarlyDeparture = 3,
  UnexpectedAbsence = 4,
  OvertimeUnscheduled = 5
}

export enum AttendanceExceptionStatus {
  Pending = 0,
  Resolved = 1,
  Waived = 2,
  Escalated = 3
}

export interface ClockEventDto {
  id: string;
  employmentId: string;
  type: number;
  source: number;
  capturedAtUtc: string;
  receivedAtUtc: string;
  sourceDeviceId?: string | null;
  correlationId?: string | null;
  actorUserId?: string | null;
  latitude?: number | null;
  longitude?: number | null;
}

export interface AttendanceExceptionDto {
  id: string;
  attendanceDayId: string;
  tenantId: string;
  employmentId: string;
  employeeNameEn?: string;
  employeeNameAr?: string;
  type: number;
  typeName: string;
  status: number;
  statusName: string;
  details: string;
  resolutionNotes?: string | null;
  resolvedByUserId?: string | null;
  resolvedAtUtc?: string | null;
  createdAtUtc: string;
}

export interface AttendanceAdjustmentDto {
  id: string;
  attendanceDayId: string;
  employmentId: string;
  adjustedWorkedMinutes: number;
  beforeWorkedMinutes: number;
  afterWorkedMinutes: number;
  reason: string;
  actorUserId: string;
  createdAtUtc: string;
  approvalRequestId?: string | null;
}

export interface AttendanceDayDto {
  id: string;
  tenantId: string;
  legalEntityId: string;
  employmentId: string;
  employeeNameEn?: string;
  employeeNameAr?: string;
  employeeNumber?: string;
  departmentNameEn?: string;
  businessDate: string;
  timezoneId: string;
  status: number;
  statusName: string;
  scheduledStartUtc?: string | null;
  scheduledEndUtc?: string | null;
  scheduledMinutes: number;
  firstClockInUtc?: string | null;
  lastClockOutUtc?: string | null;
  totalWorkedMinutes: number;
  lateMinutes: number;
  earlyDepartureMinutes: number;
  isAbsent: boolean;
  rowVersion: number;
  exceptions?: AttendanceExceptionDto[];
  adjustments?: AttendanceAdjustmentDto[];
}

export interface CaptureClockRequest {
  employmentId: string;
  type: number;
  source: number;
  capturedAtUtc?: string | null;
  sourceDeviceId?: string | null;
  correlationId?: string | null;
  latitude?: number | null;
  longitude?: number | null;
}

export interface AdjustAttendanceRequest {
  adjustedWorkedMinutes: number;
  reason: string;
  rowVersion: number;
}

export interface ResolveExceptionRequest {
  resolutionNotes: string;
  waive?: boolean;
}

// ==========================================
// Phase 3 — Leave Module Contracts
// ==========================================

export enum LeaveCategory {
  Annual = 0,
  Sick = 1,
  Maternity = 2,
  Paternity = 3,
  Bereavement = 4,
  Hajj = 5,
  Marriage = 6,
  Unpaid = 7,
  Emergency = 8
}

export enum LeaveRequestStatus {
  Draft = 0,
  PendingApproval = 1,
  Approved = 2,
  Rejected = 3,
  Cancelled = 4
}

export interface LeaveTypeDto {
  id: string;
  tenantId: string;
  legalEntityId: string;
  code: string;
  nameEn: string;
  nameAr: string;
  category: number;
  categoryName: string;
  isPaid: boolean;
  requiresAttachment: boolean;
  allowHalfDay: boolean;
  isActive: boolean;
}

export interface LeaveBalanceDto {
  id: string;
  employmentId: string;
  leaveTypeId: string;
  leaveTypeNameEn: string;
  leaveTypeNameAr: string;
  year: number;
  entitledDays: number;
  accruedDays: number;
  usedDays: number;
  pendingDays: number;
  availableDays: number;
  rowVersion: number;
}

export interface LeaveRequestDto {
  id: string;
  tenantId: string;
  legalEntityId: string;
  employmentId: string;
  employeeNameEn?: string;
  employeeNameAr?: string;
  employeeNumber?: string;
  departmentNameEn?: string;
  leaveTypeId: string;
  leaveTypeNameEn: string;
  leaveTypeNameAr: string;
  startDate: string;
  endDate: string;
  durationDays: number;
  durationMinutes: number;
  status: number;
  statusName: string;
  reason: string;
  attachmentDocumentId?: string | null;
  approvalRequestId?: string | null;
  rejectionReason?: string | null;
  createdAt: string;
  rowVersion: number;
}

export interface CreateLeaveRequest {
  employmentId: string;
  leaveTypeId: string;
  startDate: string;
  endDate: string;
  durationDays?: number;
  reason: string;
  attachmentDocumentId?: string | null;
}

export interface RejectLeaveRequest {
  rejectionReason: string;
  rowVersion: number;
}

// ==========================================
// Phase 3 — Approvals Module Contracts
// ==========================================

export enum ApprovalStatus {
  Pending = 0,
  Approved = 1,
  Rejected = 2,
  Cancelled = 3
}

export interface ApprovalItemDto {
  id: string;
  tenantId: string;
  legalEntityId: string;
  domain: string;
  sourceEntityId: string;
  sourceEntityType: string;
  title: string;
  summary: string;
  requesterUserId: string;
  subjectEmploymentId: string;
  subjectEmployeeNameEn?: string;
  subjectEmployeeNameAr?: string;
  currentStepOrder: number;
  totalSteps: number;
  status: number;
  statusName: string;
  createdAtUtc: string;
  rowVersion: number;
  assignedApproverId: string;
  stepOrder: number;
}

export interface ApprovalDecisionRequest {
  comments?: string | null;
  rowVersion: number;
}


