/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Workforce.Host.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChangeAssignmentRequest,
  ChangeContextRequest,
  CreateEmployeeRequest,
  CreateLocationRequest,
  CreateOrganizationUnitRequest,
  DocumentDetailDto,
  DocumentSummaryDto,
  DocumentTypeDto,
  EmployeeProfileDto,
  GetApiV1DocumentsIdDownloadParams,
  GetApiV1DocumentsParams,
  GetApiV1OrganizationUnitsParams,
  GetApiV1PeopleEmployeesParams,
  LocationDto,
  OrganizationUnitDto,
  PagedResultOfEmployeeSummaryDto,
  PostApiV1DocumentsUploadBody,
  ProblemDetails,
  RevealSensitiveFieldRequest,
  SensitiveRevealResponse,
  UpdateOrganizationUnitRequest
} from './generated.schemas';

import { customInstance } from './axios-instance';
import type { ErrorType } from './axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary System health and liveness probe
 */
export const getHealth = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/health`, method: 'GET', signal
    },
      options);
    }
  



export const getGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }

    
export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = ErrorType<unknown>


export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary System health and liveness probe
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary System readiness probe verifying database connectivity
 */
export const getReadiness = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/health/ready`, method: 'GET', signal
    },
      options);
    }
  



export const getGetReadinessQueryKey = () => {
    return [
    `/health/ready`
    ] as const;
    }

    
export const getGetReadinessQueryOptions = <TData = Awaited<ReturnType<typeof getReadiness>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReadiness>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReadinessQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReadiness>>> = ({ signal }) => getReadiness(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReadiness>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReadinessQueryResult = NonNullable<Awaited<ReturnType<typeof getReadiness>>>
export type GetReadinessQueryError = ErrorType<unknown>


export function useGetReadiness<TData = Awaited<ReturnType<typeof getReadiness>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReadiness>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReadiness>>,
          TError,
          Awaited<ReturnType<typeof getReadiness>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReadiness<TData = Awaited<ReturnType<typeof getReadiness>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReadiness>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReadiness>>,
          TError,
          Awaited<ReturnType<typeof getReadiness>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReadiness<TData = Awaited<ReturnType<typeof getReadiness>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReadiness>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary System readiness probe verifying database connectivity
 */

export function useGetReadiness<TData = Awaited<ReturnType<typeof getReadiness>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReadiness>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReadinessQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getApiJobsJobId = (
    jobId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/jobs/${jobId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiJobsJobIdQueryKey = (jobId?: string,) => {
    return [
    `/api/jobs/${jobId}`
    ] as const;
    }

    
export const getGetApiJobsJobIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiJobsJobId>>, TError = ErrorType<unknown>>(jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJobsJobId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiJobsJobIdQueryKey(jobId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiJobsJobId>>> = ({ signal }) => getApiJobsJobId(jobId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(jobId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiJobsJobId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiJobsJobIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiJobsJobId>>>
export type GetApiJobsJobIdQueryError = ErrorType<unknown>


export function useGetApiJobsJobId<TData = Awaited<ReturnType<typeof getApiJobsJobId>>, TError = ErrorType<unknown>>(
 jobId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJobsJobId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiJobsJobId>>,
          TError,
          Awaited<ReturnType<typeof getApiJobsJobId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiJobsJobId<TData = Awaited<ReturnType<typeof getApiJobsJobId>>, TError = ErrorType<unknown>>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJobsJobId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiJobsJobId>>,
          TError,
          Awaited<ReturnType<typeof getApiJobsJobId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiJobsJobId<TData = Awaited<ReturnType<typeof getApiJobsJobId>>, TError = ErrorType<unknown>>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJobsJobId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiJobsJobId<TData = Awaited<ReturnType<typeof getApiJobsJobId>>, TError = ErrorType<unknown>>(
 jobId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiJobsJobId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiJobsJobIdQueryOptions(jobId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getApiSessionCurrent = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/session/current`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiSessionCurrentQueryKey = () => {
    return [
    `/api/session/current`
    ] as const;
    }

    
export const getGetApiSessionCurrentQueryOptions = <TData = Awaited<ReturnType<typeof getApiSessionCurrent>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionCurrent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSessionCurrentQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSessionCurrent>>> = ({ signal }) => getApiSessionCurrent(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSessionCurrent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSessionCurrentQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSessionCurrent>>>
export type GetApiSessionCurrentQueryError = ErrorType<unknown>


export function useGetApiSessionCurrent<TData = Awaited<ReturnType<typeof getApiSessionCurrent>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionCurrent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionCurrent>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionCurrent<TData = Awaited<ReturnType<typeof getApiSessionCurrent>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionCurrent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSessionCurrent>>,
          TError,
          Awaited<ReturnType<typeof getApiSessionCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSessionCurrent<TData = Awaited<ReturnType<typeof getApiSessionCurrent>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionCurrent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSessionCurrent<TData = Awaited<ReturnType<typeof getApiSessionCurrent>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSessionCurrent>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSessionCurrentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const postApiSessionContext = (
    changeContextRequest: ChangeContextRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/session/context`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changeContextRequest, signal
    },
      options);
    }
  


export const getPostApiSessionContextMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessionContext>>, TError,{data: ChangeContextRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSessionContext>>, TError,{data: ChangeContextRequest}, TContext> => {

const mutationKey = ['postApiSessionContext'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSessionContext>>, {data: ChangeContextRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiSessionContext(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSessionContextMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSessionContext>>>
    export type PostApiSessionContextMutationBody = ChangeContextRequest
    export type PostApiSessionContextMutationError = ErrorType<unknown>

    export const usePostApiSessionContext = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSessionContext>>, TError,{data: ChangeContextRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSessionContext>>,
        TError,
        {data: ChangeContextRequest},
        TContext
      > => {

      const mutationOptions = getPostApiSessionContextMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiV1DocumentsTypes = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentTypeDto[]>(
      {url: `/api/v1/documents/types`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1DocumentsTypesQueryKey = () => {
    return [
    `/api/v1/documents/types`
    ] as const;
    }

    
export const getGetApiV1DocumentsTypesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1DocumentsTypes>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1DocumentsTypesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1DocumentsTypes>>> = ({ signal }) => getApiV1DocumentsTypes(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1DocumentsTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1DocumentsTypes>>>
export type GetApiV1DocumentsTypesQueryError = ErrorType<unknown>


export function useGetApiV1DocumentsTypes<TData = Awaited<ReturnType<typeof getApiV1DocumentsTypes>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DocumentsTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DocumentsTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DocumentsTypes<TData = Awaited<ReturnType<typeof getApiV1DocumentsTypes>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DocumentsTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DocumentsTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DocumentsTypes<TData = Awaited<ReturnType<typeof getApiV1DocumentsTypes>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1DocumentsTypes<TData = Awaited<ReturnType<typeof getApiV1DocumentsTypes>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1DocumentsTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getApiV1Documents = (
    params?: GetApiV1DocumentsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentSummaryDto[]>(
      {url: `/api/v1/documents`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV1DocumentsQueryKey = (params?: GetApiV1DocumentsParams,) => {
    return [
    `/api/v1/documents`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1DocumentsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1Documents>>, TError = ErrorType<unknown>>(params?: GetApiV1DocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Documents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1DocumentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1Documents>>> = ({ signal }) => getApiV1Documents(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1Documents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1DocumentsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1Documents>>>
export type GetApiV1DocumentsQueryError = ErrorType<unknown>


export function useGetApiV1Documents<TData = Awaited<ReturnType<typeof getApiV1Documents>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV1DocumentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Documents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Documents>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Documents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Documents<TData = Awaited<ReturnType<typeof getApiV1Documents>>, TError = ErrorType<unknown>>(
 params?: GetApiV1DocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Documents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Documents>>,
          TError,
          Awaited<ReturnType<typeof getApiV1Documents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1Documents<TData = Awaited<ReturnType<typeof getApiV1Documents>>, TError = ErrorType<unknown>>(
 params?: GetApiV1DocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Documents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1Documents<TData = Awaited<ReturnType<typeof getApiV1Documents>>, TError = ErrorType<unknown>>(
 params?: GetApiV1DocumentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1Documents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1DocumentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getApiV1DocumentsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<DocumentDetailDto>(
      {url: `/api/v1/documents/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1DocumentsIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/documents/${id}`
    ] as const;
    }

    
export const getGetApiV1DocumentsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1DocumentsId>>, TError = ErrorType<ProblemDetails>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1DocumentsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1DocumentsId>>> = ({ signal }) => getApiV1DocumentsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1DocumentsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1DocumentsId>>>
export type GetApiV1DocumentsIdQueryError = ErrorType<ProblemDetails>


export function useGetApiV1DocumentsId<TData = Awaited<ReturnType<typeof getApiV1DocumentsId>>, TError = ErrorType<ProblemDetails>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DocumentsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DocumentsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DocumentsId<TData = Awaited<ReturnType<typeof getApiV1DocumentsId>>, TError = ErrorType<ProblemDetails>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DocumentsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DocumentsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DocumentsId<TData = Awaited<ReturnType<typeof getApiV1DocumentsId>>, TError = ErrorType<ProblemDetails>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1DocumentsId<TData = Awaited<ReturnType<typeof getApiV1DocumentsId>>, TError = ErrorType<ProblemDetails>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1DocumentsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const getApiV1DocumentsIdDownload = (
    id: string,
    params?: GetApiV1DocumentsIdDownloadParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/api/v1/documents/${id}/download`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV1DocumentsIdDownloadQueryKey = (id?: string,
    params?: GetApiV1DocumentsIdDownloadParams,) => {
    return [
    `/api/v1/documents/${id}/download`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1DocumentsIdDownloadQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>, TError = ErrorType<ProblemDetails>>(id: string,
    params?: GetApiV1DocumentsIdDownloadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1DocumentsIdDownloadQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>> = ({ signal }) => getApiV1DocumentsIdDownload(id,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1DocumentsIdDownloadQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>>
export type GetApiV1DocumentsIdDownloadQueryError = ErrorType<ProblemDetails>


export function useGetApiV1DocumentsIdDownload<TData = Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>, TError = ErrorType<ProblemDetails>>(
 id: string,
    params: undefined |  GetApiV1DocumentsIdDownloadParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DocumentsIdDownload<TData = Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>, TError = ErrorType<ProblemDetails>>(
 id: string,
    params?: GetApiV1DocumentsIdDownloadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>,
          TError,
          Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1DocumentsIdDownload<TData = Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>, TError = ErrorType<ProblemDetails>>(
 id: string,
    params?: GetApiV1DocumentsIdDownloadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1DocumentsIdDownload<TData = Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>, TError = ErrorType<ProblemDetails>>(
 id: string,
    params?: GetApiV1DocumentsIdDownloadParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1DocumentsIdDownload>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1DocumentsIdDownloadQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const postApiV1DocumentsUpload = (
    postApiV1DocumentsUploadBody: PostApiV1DocumentsUploadBody,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      const formUrlEncoded = new URLSearchParams();
if(postApiV1DocumentsUploadBody.OwnerType !== undefined) {
 formUrlEncoded.append(`OwnerType`, postApiV1DocumentsUploadBody.OwnerType)
 }
if(postApiV1DocumentsUploadBody.OwnerId !== undefined) {
 formUrlEncoded.append(`OwnerId`, postApiV1DocumentsUploadBody.OwnerId)
 }
if(postApiV1DocumentsUploadBody.DocumentTypeId !== undefined) {
 formUrlEncoded.append(`DocumentTypeId`, postApiV1DocumentsUploadBody.DocumentTypeId)
 }
if(postApiV1DocumentsUploadBody.Title !== undefined) {
 formUrlEncoded.append(`Title`, postApiV1DocumentsUploadBody.Title)
 }
if(postApiV1DocumentsUploadBody.ExpiryDate !== undefined) {
 formUrlEncoded.append(`ExpiryDate`, postApiV1DocumentsUploadBody.ExpiryDate)
 }
if(postApiV1DocumentsUploadBody.File !== undefined) {
 formUrlEncoded.append(`File`, postApiV1DocumentsUploadBody.File as any)
 }

      return customInstance<DocumentDetailDto>(
      {url: `/api/v1/documents/upload`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      options);
    }
  


export const getPostApiV1DocumentsUploadMutationOptions = <TError = ErrorType<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1DocumentsUpload>>, TError,{data: PostApiV1DocumentsUploadBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1DocumentsUpload>>, TError,{data: PostApiV1DocumentsUploadBody}, TContext> => {

const mutationKey = ['postApiV1DocumentsUpload'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1DocumentsUpload>>, {data: PostApiV1DocumentsUploadBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1DocumentsUpload(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1DocumentsUploadMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1DocumentsUpload>>>
    export type PostApiV1DocumentsUploadMutationBody = PostApiV1DocumentsUploadBody
    export type PostApiV1DocumentsUploadMutationError = ErrorType<ProblemDetails>

    export const usePostApiV1DocumentsUpload = <TError = ErrorType<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1DocumentsUpload>>, TError,{data: PostApiV1DocumentsUploadBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1DocumentsUpload>>,
        TError,
        {data: PostApiV1DocumentsUploadBody},
        TContext
      > => {

      const mutationOptions = getPostApiV1DocumentsUploadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiV1OrganizationUnits = (
    params?: GetApiV1OrganizationUnitsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrganizationUnitDto[]>(
      {url: `/api/v1/organization/units`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV1OrganizationUnitsQueryKey = (params?: GetApiV1OrganizationUnitsParams,) => {
    return [
    `/api/v1/organization/units`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1OrganizationUnitsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1OrganizationUnits>>, TError = ErrorType<unknown>>(params?: GetApiV1OrganizationUnitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationUnits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1OrganizationUnitsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1OrganizationUnits>>> = ({ signal }) => getApiV1OrganizationUnits(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationUnits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1OrganizationUnitsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1OrganizationUnits>>>
export type GetApiV1OrganizationUnitsQueryError = ErrorType<unknown>


export function useGetApiV1OrganizationUnits<TData = Awaited<ReturnType<typeof getApiV1OrganizationUnits>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV1OrganizationUnitsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationUnits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1OrganizationUnits>>,
          TError,
          Awaited<ReturnType<typeof getApiV1OrganizationUnits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1OrganizationUnits<TData = Awaited<ReturnType<typeof getApiV1OrganizationUnits>>, TError = ErrorType<unknown>>(
 params?: GetApiV1OrganizationUnitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationUnits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1OrganizationUnits>>,
          TError,
          Awaited<ReturnType<typeof getApiV1OrganizationUnits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1OrganizationUnits<TData = Awaited<ReturnType<typeof getApiV1OrganizationUnits>>, TError = ErrorType<unknown>>(
 params?: GetApiV1OrganizationUnitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationUnits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1OrganizationUnits<TData = Awaited<ReturnType<typeof getApiV1OrganizationUnits>>, TError = ErrorType<unknown>>(
 params?: GetApiV1OrganizationUnitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationUnits>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1OrganizationUnitsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const postApiV1OrganizationUnits = (
    createOrganizationUnitRequest: CreateOrganizationUnitRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrganizationUnitDto>(
      {url: `/api/v1/organization/units`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOrganizationUnitRequest, signal
    },
      options);
    }
  


export const getPostApiV1OrganizationUnitsMutationOptions = <TError = ErrorType<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1OrganizationUnits>>, TError,{data: CreateOrganizationUnitRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1OrganizationUnits>>, TError,{data: CreateOrganizationUnitRequest}, TContext> => {

const mutationKey = ['postApiV1OrganizationUnits'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1OrganizationUnits>>, {data: CreateOrganizationUnitRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1OrganizationUnits(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1OrganizationUnitsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1OrganizationUnits>>>
    export type PostApiV1OrganizationUnitsMutationBody = CreateOrganizationUnitRequest
    export type PostApiV1OrganizationUnitsMutationError = ErrorType<ProblemDetails>

    export const usePostApiV1OrganizationUnits = <TError = ErrorType<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1OrganizationUnits>>, TError,{data: CreateOrganizationUnitRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1OrganizationUnits>>,
        TError,
        {data: CreateOrganizationUnitRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1OrganizationUnitsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiV1OrganizationUnitsId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<OrganizationUnitDto>(
      {url: `/api/v1/organization/units/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1OrganizationUnitsIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/organization/units/${id}`
    ] as const;
    }

    
export const getGetApiV1OrganizationUnitsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>, TError = ErrorType<ProblemDetails>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1OrganizationUnitsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>> = ({ signal }) => getApiV1OrganizationUnitsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1OrganizationUnitsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>>
export type GetApiV1OrganizationUnitsIdQueryError = ErrorType<ProblemDetails>


export function useGetApiV1OrganizationUnitsId<TData = Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>, TError = ErrorType<ProblemDetails>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1OrganizationUnitsId<TData = Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>, TError = ErrorType<ProblemDetails>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1OrganizationUnitsId<TData = Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>, TError = ErrorType<ProblemDetails>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1OrganizationUnitsId<TData = Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>, TError = ErrorType<ProblemDetails>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationUnitsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1OrganizationUnitsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const putApiV1OrganizationUnitsId = (
    id: string,
    updateOrganizationUnitRequest: UpdateOrganizationUnitRequest,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<OrganizationUnitDto>(
      {url: `/api/v1/organization/units/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateOrganizationUnitRequest
    },
      options);
    }
  


export const getPutApiV1OrganizationUnitsIdMutationOptions = <TError = ErrorType<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1OrganizationUnitsId>>, TError,{id: string;data: UpdateOrganizationUnitRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV1OrganizationUnitsId>>, TError,{id: string;data: UpdateOrganizationUnitRequest}, TContext> => {

const mutationKey = ['putApiV1OrganizationUnitsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV1OrganizationUnitsId>>, {id: string;data: UpdateOrganizationUnitRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV1OrganizationUnitsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV1OrganizationUnitsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV1OrganizationUnitsId>>>
    export type PutApiV1OrganizationUnitsIdMutationBody = UpdateOrganizationUnitRequest
    export type PutApiV1OrganizationUnitsIdMutationError = ErrorType<ProblemDetails>

    export const usePutApiV1OrganizationUnitsId = <TError = ErrorType<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV1OrganizationUnitsId>>, TError,{id: string;data: UpdateOrganizationUnitRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV1OrganizationUnitsId>>,
        TError,
        {id: string;data: UpdateOrganizationUnitRequest},
        TContext
      > => {

      const mutationOptions = getPutApiV1OrganizationUnitsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiV1OrganizationLocations = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LocationDto[]>(
      {url: `/api/v1/organization/locations`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1OrganizationLocationsQueryKey = () => {
    return [
    `/api/v1/organization/locations`
    ] as const;
    }

    
export const getGetApiV1OrganizationLocationsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1OrganizationLocations>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationLocations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1OrganizationLocationsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1OrganizationLocations>>> = ({ signal }) => getApiV1OrganizationLocations(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationLocations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1OrganizationLocationsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1OrganizationLocations>>>
export type GetApiV1OrganizationLocationsQueryError = ErrorType<unknown>


export function useGetApiV1OrganizationLocations<TData = Awaited<ReturnType<typeof getApiV1OrganizationLocations>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationLocations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1OrganizationLocations>>,
          TError,
          Awaited<ReturnType<typeof getApiV1OrganizationLocations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1OrganizationLocations<TData = Awaited<ReturnType<typeof getApiV1OrganizationLocations>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationLocations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1OrganizationLocations>>,
          TError,
          Awaited<ReturnType<typeof getApiV1OrganizationLocations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1OrganizationLocations<TData = Awaited<ReturnType<typeof getApiV1OrganizationLocations>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationLocations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1OrganizationLocations<TData = Awaited<ReturnType<typeof getApiV1OrganizationLocations>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1OrganizationLocations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1OrganizationLocationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const postApiV1OrganizationLocations = (
    createLocationRequest: CreateLocationRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<LocationDto>(
      {url: `/api/v1/organization/locations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createLocationRequest, signal
    },
      options);
    }
  


export const getPostApiV1OrganizationLocationsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1OrganizationLocations>>, TError,{data: CreateLocationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1OrganizationLocations>>, TError,{data: CreateLocationRequest}, TContext> => {

const mutationKey = ['postApiV1OrganizationLocations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1OrganizationLocations>>, {data: CreateLocationRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1OrganizationLocations(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1OrganizationLocationsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1OrganizationLocations>>>
    export type PostApiV1OrganizationLocationsMutationBody = CreateLocationRequest
    export type PostApiV1OrganizationLocationsMutationError = ErrorType<unknown>

    export const usePostApiV1OrganizationLocations = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1OrganizationLocations>>, TError,{data: CreateLocationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1OrganizationLocations>>,
        TError,
        {data: CreateLocationRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1OrganizationLocationsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiV1PeopleEmployees = (
    params?: GetApiV1PeopleEmployeesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PagedResultOfEmployeeSummaryDto>(
      {url: `/api/v1/people/employees`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiV1PeopleEmployeesQueryKey = (params?: GetApiV1PeopleEmployeesParams,) => {
    return [
    `/api/v1/people/employees`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiV1PeopleEmployeesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PeopleEmployees>>, TError = ErrorType<unknown>>(params?: GetApiV1PeopleEmployeesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PeopleEmployees>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PeopleEmployeesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PeopleEmployees>>> = ({ signal }) => getApiV1PeopleEmployees(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PeopleEmployees>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PeopleEmployeesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PeopleEmployees>>>
export type GetApiV1PeopleEmployeesQueryError = ErrorType<unknown>


export function useGetApiV1PeopleEmployees<TData = Awaited<ReturnType<typeof getApiV1PeopleEmployees>>, TError = ErrorType<unknown>>(
 params: undefined |  GetApiV1PeopleEmployeesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PeopleEmployees>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PeopleEmployees>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PeopleEmployees>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PeopleEmployees<TData = Awaited<ReturnType<typeof getApiV1PeopleEmployees>>, TError = ErrorType<unknown>>(
 params?: GetApiV1PeopleEmployeesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PeopleEmployees>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PeopleEmployees>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PeopleEmployees>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PeopleEmployees<TData = Awaited<ReturnType<typeof getApiV1PeopleEmployees>>, TError = ErrorType<unknown>>(
 params?: GetApiV1PeopleEmployeesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PeopleEmployees>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1PeopleEmployees<TData = Awaited<ReturnType<typeof getApiV1PeopleEmployees>>, TError = ErrorType<unknown>>(
 params?: GetApiV1PeopleEmployeesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PeopleEmployees>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PeopleEmployeesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const postApiV1PeopleEmployees = (
    createEmployeeRequest: CreateEmployeeRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EmployeeProfileDto>(
      {url: `/api/v1/people/employees`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createEmployeeRequest, signal
    },
      options);
    }
  


export const getPostApiV1PeopleEmployeesMutationOptions = <TError = ErrorType<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PeopleEmployees>>, TError,{data: CreateEmployeeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PeopleEmployees>>, TError,{data: CreateEmployeeRequest}, TContext> => {

const mutationKey = ['postApiV1PeopleEmployees'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PeopleEmployees>>, {data: CreateEmployeeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiV1PeopleEmployees(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PeopleEmployeesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PeopleEmployees>>>
    export type PostApiV1PeopleEmployeesMutationBody = CreateEmployeeRequest
    export type PostApiV1PeopleEmployeesMutationError = ErrorType<ProblemDetails>

    export const usePostApiV1PeopleEmployees = <TError = ErrorType<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PeopleEmployees>>, TError,{data: CreateEmployeeRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PeopleEmployees>>,
        TError,
        {data: CreateEmployeeRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1PeopleEmployeesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const getApiV1PeopleEmployeesId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EmployeeProfileDto>(
      {url: `/api/v1/people/employees/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiV1PeopleEmployeesIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/people/employees/${id}`
    ] as const;
    }

    
export const getGetApiV1PeopleEmployeesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>, TError = ErrorType<ProblemDetails>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV1PeopleEmployeesIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>> = ({ signal }) => getApiV1PeopleEmployeesId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV1PeopleEmployeesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>>
export type GetApiV1PeopleEmployeesIdQueryError = ErrorType<ProblemDetails>


export function useGetApiV1PeopleEmployeesId<TData = Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>, TError = ErrorType<ProblemDetails>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PeopleEmployeesId<TData = Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>, TError = ErrorType<ProblemDetails>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV1PeopleEmployeesId<TData = Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>, TError = ErrorType<ProblemDetails>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV1PeopleEmployeesId<TData = Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>, TError = ErrorType<ProblemDetails>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV1PeopleEmployeesId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV1PeopleEmployeesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export const postApiV1PeopleEmployeesIdAssignment = (
    id: string,
    changeAssignmentRequest: ChangeAssignmentRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<EmployeeProfileDto>(
      {url: `/api/v1/people/employees/${id}/assignment`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changeAssignmentRequest, signal
    },
      options);
    }
  


export const getPostApiV1PeopleEmployeesIdAssignmentMutationOptions = <TError = ErrorType<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PeopleEmployeesIdAssignment>>, TError,{id: string;data: ChangeAssignmentRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PeopleEmployeesIdAssignment>>, TError,{id: string;data: ChangeAssignmentRequest}, TContext> => {

const mutationKey = ['postApiV1PeopleEmployeesIdAssignment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PeopleEmployeesIdAssignment>>, {id: string;data: ChangeAssignmentRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1PeopleEmployeesIdAssignment(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PeopleEmployeesIdAssignmentMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PeopleEmployeesIdAssignment>>>
    export type PostApiV1PeopleEmployeesIdAssignmentMutationBody = ChangeAssignmentRequest
    export type PostApiV1PeopleEmployeesIdAssignmentMutationError = ErrorType<ProblemDetails>

    export const usePostApiV1PeopleEmployeesIdAssignment = <TError = ErrorType<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PeopleEmployeesIdAssignment>>, TError,{id: string;data: ChangeAssignmentRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PeopleEmployeesIdAssignment>>,
        TError,
        {id: string;data: ChangeAssignmentRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1PeopleEmployeesIdAssignmentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const postApiV1PeopleEmployeesIdRevealSensitive = (
    id: string,
    revealSensitiveFieldRequest: RevealSensitiveFieldRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<SensitiveRevealResponse>(
      {url: `/api/v1/people/employees/${id}/reveal-sensitive`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: revealSensitiveFieldRequest, signal
    },
      options);
    }
  


export const getPostApiV1PeopleEmployeesIdRevealSensitiveMutationOptions = <TError = ErrorType<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PeopleEmployeesIdRevealSensitive>>, TError,{id: string;data: RevealSensitiveFieldRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1PeopleEmployeesIdRevealSensitive>>, TError,{id: string;data: RevealSensitiveFieldRequest}, TContext> => {

const mutationKey = ['postApiV1PeopleEmployeesIdRevealSensitive'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1PeopleEmployeesIdRevealSensitive>>, {id: string;data: RevealSensitiveFieldRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1PeopleEmployeesIdRevealSensitive(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1PeopleEmployeesIdRevealSensitiveMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1PeopleEmployeesIdRevealSensitive>>>
    export type PostApiV1PeopleEmployeesIdRevealSensitiveMutationBody = RevealSensitiveFieldRequest
    export type PostApiV1PeopleEmployeesIdRevealSensitiveMutationError = ErrorType<ProblemDetails>

    export const usePostApiV1PeopleEmployeesIdRevealSensitive = <TError = ErrorType<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1PeopleEmployeesIdRevealSensitive>>, TError,{id: string;data: RevealSensitiveFieldRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1PeopleEmployeesIdRevealSensitive>>,
        TError,
        {id: string;data: RevealSensitiveFieldRequest},
        TContext
      > => {

      const mutationOptions = getPostApiV1PeopleEmployeesIdRevealSensitiveMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
